// Code generated by wiregen from shared/wire/schema.wire. DO NOT EDIT.

package wire

import (
	"fmt"

	"github.com/devarminas/marque/server/internal/wire/codec"
)

// SchemaHash identifies the schema this file was generated from.
const SchemaHash uint64 = 0xf08364ad37fc2e6e

type Message interface {
	MessageID() uint32
	Channel() codec.Channel
	Append(dst []byte) ([]byte, error)
	String() string
}

type ToServer interface {
	Message
	toServer()
}

type ToClient interface {
	Message
	toClient()
}

var quantPos = codec.Quant{Min: -4096, Max: 4096, PerUnit: 100, Steps: 819200, Width: 4}

var quantWish = codec.Quant{Min: -1, Max: 1, PerUnit: 100, Steps: 200, Width: 1}

// PlayerId pairs a slot index with the generation that slot had when the
// entity was created, so a reused index never names the old entity.
type PlayerId struct {
	Index uint32
	Gen   uint32
}

func (v PlayerId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodePlayerId(r *codec.Reader) (v PlayerId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v PlayerId) String() string { return fmt.Sprintf("PlayerId(%d/%d)", v.Index, v.Gen) }

// NpcId pairs a slot index with the generation that slot had when the
// entity was created, so a reused index never names the old entity.
type NpcId struct {
	Index uint32
	Gen   uint32
}

func (v NpcId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeNpcId(r *codec.Reader) (v NpcId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v NpcId) String() string { return fmt.Sprintf("NpcId(%d/%d)", v.Index, v.Gen) }

// ItemId pairs a slot index with the generation that slot had when the
// entity was created, so a reused index never names the old entity.
type ItemId struct {
	Index uint32
	Gen   uint32
}

func (v ItemId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeItemId(r *codec.Reader) (v ItemId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v ItemId) String() string { return fmt.Sprintf("ItemId(%d/%d)", v.Index, v.Gen) }

// NodeId pairs a slot index with the generation that slot had when the
// entity was created, so a reused index never names the old entity.
type NodeId struct {
	Index uint32
	Gen   uint32
}

func (v NodeId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeNodeId(r *codec.Reader) (v NodeId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v NodeId) String() string { return fmt.Sprintf("NodeId(%d/%d)", v.Index, v.Gen) }

type RefuseReason uint32

const (
	RefuseReasonUnknownAbility   RefuseReason = 1
	RefuseReasonNoTarget         RefuseReason = 2
	RefuseReasonWrongTarget      RefuseReason = 3
	RefuseReasonInsufficientMana RefuseReason = 4
	RefuseReasonOutOfRange       RefuseReason = 5
	RefuseReasonCooldown         RefuseReason = 6
	RefuseReasonDead             RefuseReason = 7
)

func (v RefuseReason) String() string {
	switch v {
	case RefuseReasonUnknownAbility:
		return "unknown_ability"
	case RefuseReasonNoTarget:
		return "no_target"
	case RefuseReasonWrongTarget:
		return "wrong_target"
	case RefuseReasonInsufficientMana:
		return "insufficient_mana"
	case RefuseReasonOutOfRange:
		return "out_of_range"
	case RefuseReasonCooldown:
		return "cooldown"
	case RefuseReasonDead:
		return "dead"
	}
	return fmt.Sprintf("RefuseReason(%d)", uint32(v))
}

func (v RefuseReason) valid() bool {
	switch v {
	case RefuseReasonUnknownAbility, RefuseReasonNoTarget, RefuseReasonWrongTarget, RefuseReasonInsufficientMana, RefuseReasonOutOfRange, RefuseReasonCooldown, RefuseReasonDead:
		return true
	}
	return false
}

func (v RefuseReason) encode(w *codec.Writer) {
	if !v.valid() {
		w.Fail(codec.ErrBadEnum)
		return
	}
	w.Varint(uint32(v))
}

func decodeRefuseReason(r *codec.Reader) RefuseReason {
	v := RefuseReason(r.Varint())
	if r.Err() == nil && !v.valid() {
		r.Fail(codec.ErrBadEnum)
	}
	return v
}

type Input struct {
	Dx   float64
	Dz   float64
	Jump bool
	Seq  uint32
}

func (v Input) encode(w *codec.Writer) {
	w.Quant(v.Dx, quantWish)
	w.Quant(v.Dz, quantWish)
	w.Bool(v.Jump)
	w.U32(v.Seq)
}

func decodeInput(r *codec.Reader) (v Input) {
	v.Dx = r.Quant(quantWish)
	v.Dz = r.Quant(quantWish)
	v.Jump = r.Bool()
	v.Seq = r.U32()
	return v
}

func (v Input) String() string {
	return fmt.Sprintf("input{dx:%v dz:%v jump:%v seq:%v}", v.Dx, v.Dz, v.Jump, v.Seq)
}

func (Input) MessageID() uint32 { return 1 }

func (Input) Channel() codec.Channel { return codec.ChannelInput }

func (Input) toServer() {}

func (v Input) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(1)
	v.encode(&w)
	return w.Result()
}

type Pose struct {
	Id PlayerId
	X  float64
	Y  float64
	Z  float64
}

func (v Pose) encode(w *codec.Writer) {
	v.Id.encode(w)
	w.Quant(v.X, quantPos)
	w.Quant(v.Y, quantPos)
	w.Quant(v.Z, quantPos)
}

func decodePose(r *codec.Reader) (v Pose) {
	v.Id = decodePlayerId(r)
	v.X = r.Quant(quantPos)
	v.Y = r.Quant(quantPos)
	v.Z = r.Quant(quantPos)
	return v
}

func (v Pose) String() string {
	return fmt.Sprintf("pose{id:%v x:%v y:%v z:%v}", v.Id, v.X, v.Y, v.Z)
}

func (Pose) MessageID() uint32 { return 2 }

func (Pose) Channel() codec.Channel { return codec.ChannelState }

func (Pose) toClient() {}

func (v Pose) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(2)
	v.encode(&w)
	return w.Result()
}

type Hp struct {
	Id    PlayerId
	Hp    uint32
	MaxHp uint32
}

func (v Hp) encode(w *codec.Writer) {
	v.Id.encode(w)
	w.U32(v.Hp)
	w.U32(v.MaxHp)
}

func decodeHp(r *codec.Reader) (v Hp) {
	v.Id = decodePlayerId(r)
	v.Hp = r.U32()
	v.MaxHp = r.U32()
	return v
}

func (v Hp) String() string {
	return fmt.Sprintf("hp{id:%v hp:%v max_hp:%v}", v.Id, v.Hp, v.MaxHp)
}

func (Hp) MessageID() uint32 { return 3 }

func (Hp) Channel() codec.Channel { return codec.ChannelState }

func (Hp) toClient() {}

func (v Hp) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(3)
	v.encode(&w)
	return w.Result()
}

type Refused struct {
	Tick   uint32
	Seq    uint32
	Reason RefuseReason
}

func (v Refused) encode(w *codec.Writer) {
	w.U32(v.Tick)
	w.U32(v.Seq)
	v.Reason.encode(w)
}

func decodeRefused(r *codec.Reader) (v Refused) {
	v.Tick = r.U32()
	v.Seq = r.U32()
	v.Reason = decodeRefuseReason(r)
	return v
}

func (v Refused) String() string {
	return fmt.Sprintf("refused{tick:%v seq:%v reason:%v}", v.Tick, v.Seq, v.Reason)
}

func (Refused) MessageID() uint32 { return 4 }

func (Refused) Channel() codec.Channel { return codec.ChannelEvents }

func (Refused) toClient() {}

func (v Refused) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(4)
	v.encode(&w)
	return w.Result()
}

// DecodeToServer decodes exactly one message; any byte left over is an error.
func DecodeToServer(b []byte) (ToServer, error) {
	r := codec.NewReader(b)
	var m ToServer
	switch r.Varint() {
	case 1:
		m = decodeInput(&r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

// DecodeToClient decodes exactly one message; any byte left over is an error.
func DecodeToClient(b []byte) (ToClient, error) {
	r := codec.NewReader(b)
	var m ToClient
	switch r.Varint() {
	case 2:
		m = decodePose(&r)
	case 3:
		m = decodeHp(&r)
	case 4:
		m = decodeRefused(&r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}
