// Code generated by wiregen from shared/wire/schema.wire. DO NOT EDIT.

package wire

import (
	"fmt"
	"strconv"

	"github.com/devarminas/marque/server/internal/wire/codec"
)

const SchemaHash uint64 = 0x60dfa19f4dc9df6f

type Message interface {
	MessageID() uint32
	Channel() codec.Channel
	Append(dst []byte) ([]byte, error)
	String() string
}

type StateMsg interface {
	Message
	stateMsg()
}

type EventsMsg interface {
	Message
	eventsMsg()
}

type InputMsg interface {
	Message
	inputMsg()
}

type IntentsMsg interface {
	Message
	intentsMsg()
}

var quantPos = codec.Quant{Min: -4096, Max: 4096, PerUnit: 100, Steps: 819200, Width: 4}

var quantWish = codec.Quant{Min: -1, Max: 1, PerUnit: 100, Steps: 200, Width: 1}

type PlayerId struct {
	Index uint32
	Gen   uint32
}

func (v PlayerId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodePlayerId(r *codec.Reader) (v PlayerId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v PlayerId) appendText(b []byte) []byte {
	b = append(b, "PlayerId("...)
	b = strconv.AppendUint(b, uint64(v.Index), 10)
	b = append(b, '/')
	b = strconv.AppendUint(b, uint64(v.Gen), 10)
	return append(b, ')')
}

func (v PlayerId) String() string { return string(v.appendText(nil)) }

type NpcId struct {
	Index uint32
	Gen   uint32
}

func (v NpcId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeNpcId(r *codec.Reader) (v NpcId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v NpcId) appendText(b []byte) []byte {
	b = append(b, "NpcId("...)
	b = strconv.AppendUint(b, uint64(v.Index), 10)
	b = append(b, '/')
	b = strconv.AppendUint(b, uint64(v.Gen), 10)
	return append(b, ')')
}

func (v NpcId) String() string { return string(v.appendText(nil)) }

type ItemId struct {
	Index uint32
	Gen   uint32
}

func (v ItemId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeItemId(r *codec.Reader) (v ItemId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v ItemId) appendText(b []byte) []byte {
	b = append(b, "ItemId("...)
	b = strconv.AppendUint(b, uint64(v.Index), 10)
	b = append(b, '/')
	b = strconv.AppendUint(b, uint64(v.Gen), 10)
	return append(b, ')')
}

func (v ItemId) String() string { return string(v.appendText(nil)) }

type NodeId struct {
	Index uint32
	Gen   uint32
}

func (v NodeId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeNodeId(r *codec.Reader) (v NodeId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v NodeId) appendText(b []byte) []byte {
	b = append(b, "NodeId("...)
	b = strconv.AppendUint(b, uint64(v.Index), 10)
	b = append(b, '/')
	b = strconv.AppendUint(b, uint64(v.Gen), 10)
	return append(b, ')')
}

func (v NodeId) String() string { return string(v.appendText(nil)) }

type RefuseReason uint32

const (
	RefuseReasonUnknownAbility   RefuseReason = 1
	RefuseReasonNoTarget         RefuseReason = 2
	RefuseReasonWrongTarget      RefuseReason = 3
	RefuseReasonInsufficientMana RefuseReason = 4
	RefuseReasonOutOfRange       RefuseReason = 5
	RefuseReasonCooldown         RefuseReason = 6
	RefuseReasonDead             RefuseReason = 7
)

func (v RefuseReason) String() string {
	switch v {
	case RefuseReasonUnknownAbility:
		return "unknown_ability"
	case RefuseReasonNoTarget:
		return "no_target"
	case RefuseReasonWrongTarget:
		return "wrong_target"
	case RefuseReasonInsufficientMana:
		return "insufficient_mana"
	case RefuseReasonOutOfRange:
		return "out_of_range"
	case RefuseReasonCooldown:
		return "cooldown"
	case RefuseReasonDead:
		return "dead"
	}
	return fmt.Sprintf("RefuseReason(%d)", uint32(v))
}

func (v RefuseReason) valid() bool {
	switch v {
	case RefuseReasonUnknownAbility, RefuseReasonNoTarget, RefuseReasonWrongTarget, RefuseReasonInsufficientMana, RefuseReasonOutOfRange, RefuseReasonCooldown, RefuseReasonDead:
		return true
	}
	return false
}

func (v RefuseReason) encode(w *codec.Writer) {
	if !v.valid() {
		w.Fail(codec.ErrBadEnum)
		return
	}
	w.Varint(uint32(v))
}

func decodeRefuseReason(r *codec.Reader) RefuseReason {
	v := RefuseReason(r.Varint())
	if r.Err() == nil && !v.valid() {
		r.Fail(codec.ErrBadEnum)
	}
	return v
}

type InputFields struct {
	Dx   float64
	Dz   float64
	Jump bool
	Seq  uint32
}

type Input struct {
	f InputFields
}

func (f InputFields) Build() (Input, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Input{}, err
	}
	return Input{f}, nil
}

func (v Input) Dx() float64 { return v.f.Dx }

func (v Input) Dz() float64 { return v.f.Dz }

func (v Input) Jump() bool { return v.f.Jump }

func (v Input) Seq() uint32 { return v.f.Seq }

func (f InputFields) encode(w *codec.Writer) {
	w.Quant(f.Dx, quantWish)
	w.Quant(f.Dz, quantWish)
	w.Bool(f.Jump)
	w.U32(f.Seq)
}

func decodeInput(r *codec.Reader) Input {
	var f InputFields
	f.Dx = r.Quant(quantWish)
	f.Dz = r.Quant(quantWish)
	f.Jump = r.Bool()
	f.Seq = r.U32()
	return Input{f}
}

func (f InputFields) appendText(b []byte) []byte {
	b = append(b, "input{dx:"...)
	b = strconv.AppendFloat(b, f.Dx, 'g', -1, 64)
	b = append(b, " dz:"...)
	b = strconv.AppendFloat(b, f.Dz, 'g', -1, 64)
	b = append(b, " jump:"...)
	b = strconv.AppendBool(b, f.Jump)
	b = append(b, " seq:"...)
	b = strconv.AppendUint(b, uint64(f.Seq), 10)
	return append(b, '}')
}

func (v Input) String() string { return string(v.f.appendText(nil)) }

func (Input) MessageID() uint32 { return 1 }

func (Input) Channel() codec.Channel { return codec.ChannelInput }

func (Input) inputMsg() {}

func (v Input) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(1)
	v.f.encode(&w)
	return w.Result()
}

type PoseFields struct {
	Id PlayerId
	X  float64
	Y  float64
	Z  float64
}

type Pose struct {
	f PoseFields
}

func (f PoseFields) Build() (Pose, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Pose{}, err
	}
	return Pose{f}, nil
}

func (v Pose) Id() PlayerId { return v.f.Id }

func (v Pose) X() float64 { return v.f.X }

func (v Pose) Y() float64 { return v.f.Y }

func (v Pose) Z() float64 { return v.f.Z }

func (f PoseFields) encode(w *codec.Writer) {
	f.Id.encode(w)
	w.Quant(f.X, quantPos)
	w.Quant(f.Y, quantPos)
	w.Quant(f.Z, quantPos)
}

func decodePose(r *codec.Reader) Pose {
	var f PoseFields
	f.Id = decodePlayerId(r)
	f.X = r.Quant(quantPos)
	f.Y = r.Quant(quantPos)
	f.Z = r.Quant(quantPos)
	return Pose{f}
}

func (f PoseFields) appendText(b []byte) []byte {
	b = append(b, "pose{id:"...)
	b = f.Id.appendText(b)
	b = append(b, " x:"...)
	b = strconv.AppendFloat(b, f.X, 'g', -1, 64)
	b = append(b, " y:"...)
	b = strconv.AppendFloat(b, f.Y, 'g', -1, 64)
	b = append(b, " z:"...)
	b = strconv.AppendFloat(b, f.Z, 'g', -1, 64)
	return append(b, '}')
}

func (v Pose) String() string { return string(v.f.appendText(nil)) }

func (Pose) MessageID() uint32 { return 2 }

func (Pose) Channel() codec.Channel { return codec.ChannelState }

func (Pose) stateMsg() {}

func (v Pose) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(2)
	v.f.encode(&w)
	return w.Result()
}

type HpFields struct {
	Id    PlayerId
	Hp    uint32
	MaxHp uint32
}

type Hp struct {
	f HpFields
}

func (f HpFields) Build() (Hp, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Hp{}, err
	}
	return Hp{f}, nil
}

func (v Hp) Id() PlayerId { return v.f.Id }

func (v Hp) Hp() uint32 { return v.f.Hp }

func (v Hp) MaxHp() uint32 { return v.f.MaxHp }

func (f HpFields) encode(w *codec.Writer) {
	f.Id.encode(w)
	w.U32(f.Hp)
	w.U32(f.MaxHp)
}

func decodeHp(r *codec.Reader) Hp {
	var f HpFields
	f.Id = decodePlayerId(r)
	f.Hp = r.U32()
	f.MaxHp = r.U32()
	return Hp{f}
}

func (f HpFields) appendText(b []byte) []byte {
	b = append(b, "hp{id:"...)
	b = f.Id.appendText(b)
	b = append(b, " hp:"...)
	b = strconv.AppendUint(b, uint64(f.Hp), 10)
	b = append(b, " max_hp:"...)
	b = strconv.AppendUint(b, uint64(f.MaxHp), 10)
	return append(b, '}')
}

func (v Hp) String() string { return string(v.f.appendText(nil)) }

func (Hp) MessageID() uint32 { return 3 }

func (Hp) Channel() codec.Channel { return codec.ChannelState }

func (Hp) stateMsg() {}

func (v Hp) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(3)
	v.f.encode(&w)
	return w.Result()
}

type RefusedFields struct {
	Tick   uint32
	Seq    uint32
	Reason RefuseReason
}

type Refused struct {
	f RefusedFields
}

func (f RefusedFields) Build() (Refused, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Refused{}, err
	}
	return Refused{f}, nil
}

func (v Refused) Tick() uint32 { return v.f.Tick }

func (v Refused) Seq() uint32 { return v.f.Seq }

func (v Refused) Reason() RefuseReason { return v.f.Reason }

func (f RefusedFields) encode(w *codec.Writer) {
	w.U32(f.Tick)
	w.U32(f.Seq)
	f.Reason.encode(w)
}

func decodeRefused(r *codec.Reader) Refused {
	var f RefusedFields
	f.Tick = r.U32()
	f.Seq = r.U32()
	f.Reason = decodeRefuseReason(r)
	return Refused{f}
}

func (f RefusedFields) appendText(b []byte) []byte {
	b = append(b, "refused{tick:"...)
	b = strconv.AppendUint(b, uint64(f.Tick), 10)
	b = append(b, " seq:"...)
	b = strconv.AppendUint(b, uint64(f.Seq), 10)
	b = append(b, " reason:"...)
	b = append(b, f.Reason.String()...)
	return append(b, '}')
}

func (v Refused) String() string { return string(v.f.appendText(nil)) }

func (Refused) MessageID() uint32 { return 4 }

func (Refused) Channel() codec.Channel { return codec.ChannelEvents }

func (Refused) eventsMsg() {}

func (v Refused) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(4)
	v.f.encode(&w)
	return w.Result()
}

func DecodeNextState(r *codec.Reader) (StateMsg, error) {
	var m StateMsg
	switch r.Varint() {
	case 2:
		m = decodePose(r)
	case 3:
		m = decodeHp(r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeState(b []byte) (StateMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextState(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeNextEvents(r *codec.Reader) (EventsMsg, error) {
	var m EventsMsg
	switch r.Varint() {
	case 4:
		m = decodeRefused(r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeEvents(b []byte) (EventsMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextEvents(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeNextInput(r *codec.Reader) (InputMsg, error) {
	var m InputMsg
	switch r.Varint() {
	case 1:
		m = decodeInput(r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeInput(b []byte) (InputMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextInput(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeNextIntents(r *codec.Reader) (IntentsMsg, error) {
	var m IntentsMsg
	switch r.Varint() {
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeIntents(b []byte) (IntentsMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextIntents(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}
