#include "marque/client/domain.hpp"
#include "check.hpp"
#include "marque/transport/endpoint.hpp"
#include "marque/transport/session_seal.hpp"
#include "marque/netsim/simulator.hpp"

#include <array>
#include <cmath>
#include <iomanip>
#include <iostream>

using namespace marque;
using test::check;
namespace {
template<class M> std::vector<std::uint8_t> bytes(const M& value) {
    std::vector<std::uint8_t> out;
    check(wire::encode(value,out).has_value(),"fixture encoded");return out;
}
template<class M> bool receive(client::Assembler& core,const M& value,std::int64_t now=400000) {
    transport::Received packet{};packet.reliable={bytes(value)};
    return core.receive(packet,{now}).has_value();
}
wire::EntitySnapshot row(wire::EntityId id,double x,bool optional=false) {
    wire::EntitySnapshotFields f{id,*wire::Transform::build({x,0,0}),{},{},{},{}};
    if(optional){
        f.vitals=*wire::Vitals::build({90,100,10,20});
        f.gear=*wire::Gear::build({{},{},{},{},{},"staff"});
        f.cast=*wire::CastBar::build({*wire::Casting::build({"fireball",1,38})});
        f.look=*wire::Look::build({"human"});
    }
    return *wire::EntitySnapshot::build(std::move(f));
}
wire::ResetCertificate cert(std::uint64_t epoch=2,std::uint64_t lease=42,std::uint16_t parts=2,std::uint32_t entities=2,std::uint64_t end=2,std::uint32_t next=1) {
    return *wire::ResetCertificate::build({88,epoch,lease,7,10,end,next,parts,entities});
}
wire::ResetBegin begin(const wire::ResetCertificate& c,float x=5,float y=0,float z=0) {
    return *wire::ResetBegin::build({c,*wire::MotionBaseline::build({88,c.epoch(),{7,1},10,0,x,y,z,0,0,0,true,wire::MotionMode::free,0,"village",2,128,0,40000})});
}
client::Assembler prior() {
    auto core=client::Assembler::create();
    transport::Received p{};
    p.unreliable=transport::Unreliable{10,{bytes(*wire::EntityReplace::build({row(wire::PlayerId{7,1},1,true)})),
        bytes(*wire::EntityReplace::build({row(wire::ItemId{3,1},2)})),bytes(*wire::Gone::build({wire::NodeId{77,3}}))}};
    p.reliable={bytes(*wire::Inventory::build({88,1,9,28,{*wire::BagEntry::build({0,"sword"})}})),bytes(*wire::TickClose::build({88,1,10,1,3,1}))};
    check(core.receive(p,{400000}).has_value(),"initial checkpoint received");
    auto published=core.publish(128*1024*1024);
    check(published && published->has_value(),"initial checkpoint published");return core;
}
}
int main() {
    for (const auto& pose:std::array<wire::TransformFields,3>{{{9,0,0},{5,9,0},{5,0,9}}}) {
        auto incoherent=prior();const auto old=incoherent.latest();
        const auto c=cert(2,42,1,1);
        check(incoherent.replace_lease(88,2,42,{7,1},{400000}).has_value(),"pose refusal lease selected");
        const auto owner_row=*wire::EntitySnapshot::build({wire::PlayerId{7,1},*wire::Transform::build(pose),{},{},{},{}});
        check(receive(incoherent,begin(c)) && receive(incoherent,*wire::QuestLog::build({88,2,9,{*wire::QuestEntry::build({"q","Quest","Gather","active"})}})) &&
            receive(incoherent,*wire::ResetPart::build({c,0,{owner_row}})) && receive(incoherent,*wire::ResetClose::build({c})),"incoherent three-axis baseline stages through generated bytes");
        bool prepared=false;
        const auto result=incoherent.publish(128*1024*1024,[&](const client::Events&,world::Tick)->std::expected<void,client::DomainError>{prepared=true;return {};});
        check(!result && result.error()==client::DomainError::world && !prepared,"owner pose mismatch refuses before preparation and publication");
        check(incoherent.latest()==old && incoherent.phase()==client::DomainPhase::reset_pending && !incoherent.take_reset_commit(),"pose refusal preserves old Reader and emits no commit");
        check(old->world().table<wire::Transform>().find(world::Player{7,1})->x()==1 && old->world().table<wire::Vitals>().find(world::Player{7,1})->hp()==90 &&
            old->events().event_end==1 && !old->events().owner->quests && old->events().owner->inventory->slots()[0].kind()=="sword","pose refusal retains pinned world and owner prefix");
        const auto retry=cert(3,43,1,1);
        check(incoherent.replace_lease(88,3,43,{7,1},{400000}).has_value() && receive(incoherent,begin(retry)) &&
            receive(incoherent,*wire::QuestLog::build({88,2,9,{*wire::QuestEntry::build({"q","Quest","Gather","active"})}})) &&
            receive(incoherent,*wire::ResetPart::build({retry,0,{row(wire::PlayerId{7,1},5)}})) && receive(incoherent,*wire::ResetClose::build({retry})),"coherent later lease restages unapplied prefix");
        const auto recovered=incoherent.publish(128*1024*1024);
        check(recovered && recovered->has_value() && incoherent.latest()->events().changes.size()==1 && incoherent.latest()->events().event_end==2 &&
            std::get<wire::QuestLog>(incoherent.latest()->events().changes[0]).event_seq()==2,"pose refusal leaves actual applied cursor unchanged for retry");
    }
    struct QuantizedPose {float motion;double snapshot;};
    const std::array quantized{
        QuantizedPose{.124f,.12},QuantizedPose{-.124f,-.12},
        QuantizedPose{std::nextafter(.125f,0.f),.12},QuantizedPose{.125f,.13},QuantizedPose{std::nextafter(.125f,1.f),.13},
        QuantizedPose{std::nextafter(-.125f,0.f),-.12},QuantizedPose{-.125f,-.13},QuantizedPose{std::nextafter(-.125f,-1.f),-.13},
        QuantizedPose{.12f,.12},QuantizedPose{-.12f,-.12},QuantizedPose{0.f,0},QuantizedPose{-0.f,0}};
    for (const auto& pose:quantized) for (std::size_t axis=0;axis<3;++axis) {
        auto rounded=prior();const auto c=cert(2,42,1,1,1);
        std::array<float,3> motion{};motion[axis]=pose.motion;
        std::array<double,3> snapshot{};snapshot[axis]=pose.snapshot;
        const auto owner_row=*wire::EntitySnapshot::build({wire::PlayerId{7,1},*wire::Transform::build({snapshot[0],snapshot[1],snapshot[2]}),{},{},{},{}});
        check(rounded.replace_lease(88,2,42,{7,1},{400000}).has_value() && receive(rounded,begin(c,motion[0],motion[1],motion[2])) &&
            receive(rounded,*wire::ResetPart::build({c,0,{owner_row}})) && receive(rounded,*wire::ResetClose::build({c})),"literal quantized boundary stages through generated bytes");
        const auto result=rounded.publish(128*1024*1024);
        check(result && result->has_value(),"positive and negative rounding boundaries remain legal on every axis");
        if (result && result->has_value()) {
            const auto transform=rounded.latest()->world().table<wire::Transform>().find(world::Player{7,1});
            check(transform->x()==snapshot[0] && transform->y()==snapshot[1] && transform->z()==snapshot[2],"published owner Transform has literal grid position");
            const auto& m=*rounded.latest()->events().motion;
            check(m.x()==motion[0] && m.y()==motion[1] && m.z()==motion[2],"published motion retains actual f32 position");
            const auto control=wire::decode_intents((**result).application_commit);
            check(control && std::get<wire::ResetCommit>(*control).certificate()==c,"legal rounded pose produces exact certificate commit");
        }
    }
    for (const double source:{.1249999999,.1250000001,-.1249999999,-.1250000001}) for (std::size_t axis=0;axis<3;++axis) {
        auto rounded=prior();const auto c=cert(2,42,1,1,1);
        std::array<double,3> position{};position[axis]=source;
        const auto owner_row=*wire::EntitySnapshot::build({wire::PlayerId{7,1},*wire::Transform::build({position[0],position[1],position[2]}),{},{},{},{}});
        const double expected=std::abs(source)<.125 ? (source<0 ? -.12 : .12) : (source<0 ? -.13 : .13);
        const auto encoded_motion=*wire::OwnerMotion::build({88,2,{7,1},10,0,static_cast<float>(position[0]),static_cast<float>(position[1]),static_cast<float>(position[2]),0,0,0,true,wire::MotionMode::free,0,"village",2,128,0,40000});
        const auto decoded_motion=wire::decode_state(bytes(encoded_motion));
        check(decoded_motion && std::holds_alternative<wire::OwnerMotion>(*decoded_motion),"source double motion roundtrips actual generated OwnerMotion codec");
        const auto& source_motion=std::get<wire::OwnerMotion>(*decoded_motion);
        const auto decoded_entity=wire::decode_state(bytes(*wire::EntityReplace::build({owner_row})));
        check(decoded_entity && std::get<wire::EntityReplace>(*decoded_entity).entity().transform()==owner_row.transform(),"source double Transform roundtrips actual generated entity codec");
        check(rounded.replace_lease(88,2,42,{7,1},{400000}).has_value() &&
            receive(rounded,begin(c,source_motion.x(),source_motion.y(),source_motion.z())) &&
            receive(rounded,*wire::ResetPart::build({c,0,{owner_row}})) && receive(rounded,*wire::ResetClose::build({c})),"one source double independently encoded into f32 motion and grid snapshot");
        const auto result=rounded.publish(128*1024*1024);
        check(result && result->has_value(),"independent f32 rounding across position half-step remains legal");
        if (result && result->has_value()) {
            const auto t=rounded.latest()->world().table<wire::Transform>().find(world::Player{7,1});
            const std::array actual{t->x(),t->y(),t->z()};
            const auto& m=*rounded.latest()->events().motion;const std::array motion{m.x(),m.y(),m.z()};
            check(actual[axis]==expected && motion[axis]==(source<0 ? -.125f : .125f),"published double-source pair retains literal independent wire rounding");
            if (axis==0) std::cout<<"source double rounding source="<<std::setprecision(12)<<source<<" snapshot="<<actual[axis]<<" motion="<<motion[axis]<<'\n';
        }
    }
    for (const double mismatch:{.11,.14,-.11,-.14}) for (std::size_t axis=0;axis<3;++axis) {
        auto rounded=prior();const auto old=rounded.latest();const auto c=cert(2,42,1,1,1);
        std::array<float,3> motion{};motion[axis]=mismatch<0 ? -.125f : .125f;
        std::array<double,3> snapshot{};snapshot[axis]=mismatch;
        const auto owner_row=*wire::EntitySnapshot::build({wire::PlayerId{7,1},*wire::Transform::build({snapshot[0],snapshot[1],snapshot[2]}),{},{},{},{}});
        check(rounded.replace_lease(88,2,42,{7,1},{400000}).has_value() && receive(rounded,begin(c,motion[0],motion[1],motion[2])) &&
            receive(rounded,*wire::ResetPart::build({c,0,{owner_row}})) && receive(rounded,*wire::ResetClose::build({c})),"outside rounding interval row stages through generated bytes");
        const auto result=rounded.publish(128*1024*1024);
        check(!result && result.error()==client::DomainError::world && rounded.latest()==old && !rounded.take_reset_commit(),"adjacent grid beyond true f32 rounding interval refuses");
    }
    {
        auto absent=prior();const auto old=absent.latest();const auto c=cert(2,42,1,1,1);
        check(absent.replace_lease(88,2,42,{7,1},{400000}).has_value() && receive(absent,begin(c)) &&
            receive(absent,*wire::ResetPart::build({c,0,{row(wire::NpcId{9,1},5)}})) && receive(absent,*wire::ResetClose::build({c})),"missing owner fixture stages complete counts");
        const auto result=absent.publish(128*1024*1024);
        check(!result && result.error()==client::DomainError::state_count && absent.latest()==old && !absent.take_reset_commit(),"missing owner identity still refuses before publication");
        auto wrong=prior();check(wrong.replace_lease(88,2,42,{7,1},{400000}).has_value(),"wrong motion identity lease selected");
        const auto motion=*wire::MotionBaseline::build({88,2,{8,1},10,0,5,0,0,0,0,0,true,wire::MotionMode::free,0,"village",2,128,0,40000});
        check(!receive(wrong,*wire::ResetBegin::build({c,motion})) && wrong.latest()->events().event_end==1 && !wrong.take_reset_commit(),"wrong motion player identity still refuses");
    }
    auto core=prior();const auto pinned=core.latest();
    check(core.replace_lease(88,2,42,{7,1},{400000}).has_value(),"new lease retains checkpoint");
    check(core.latest()==pinned && core.phase()==client::DomainPhase::reset_pending,"pending phase preserves Reader checkpoint");
    const auto certificate=cert();
    check(receive(core,begin(certificate)),"reset begin received");
    check(receive(core,*wire::Inventory::build({88,1,9,28,{*wire::BagEntry::build({0,"old duplicate"})}})),"published prefix duplicate skipped by actual client cursor");
    const auto quest=*wire::QuestLog::build({88,2,9,{*wire::QuestEntry::build({"q","Quest","Gather","active"})}});
    check(receive(core,quest) && receive(core,quest),"identical pending prefix duplicate accepted once");
    const auto part1=*wire::ResetPart::build({certificate,1,{row(wire::NpcId{9,1},7)}});
    check(receive(core,part1) && receive(core,part1),"reordered indexed part duplicate accepted");
    check(receive(core,*wire::ResetClose::build({certificate})),"close may precede missing indexed part");
    auto missing=core.publish(128*1024*1024);
    check(missing && !missing->has_value() && core.latest()==pinned,"missing part publishes nothing");
    check(!receive(core,*wire::ResetPart::build({certificate,1,{row(wire::NpcId{9,1},8)}})) && core.latest()==pinned,"changed duplicate refused without publication");
    check(receive(core,*wire::ResetPart::build({certificate,0,{row(wire::PlayerId{7,1},5)}})),"remaining part received");
    auto value=core.publish(128*1024*1024);
    check(value && value->has_value(),"complete baseline published once");
    const auto current=core.latest();
    check(current->tick().value==10 && current->sample_time().microseconds==400000,"same producing tick preserves original clock anchor");
    check(current->events().epoch==2 && current->events().event_end==2 && current->events().changes.size()==1,"complete historical prefix publishes once");
    check(std::get<wire::QuestLog>(current->events().changes[0]).tick()==9 && current->events().owner->inventory->slots()[0].kind()=="sword","owner producing tick and retained client cursor preserved");
    check(current->world().entities().size()==2 && !current->world().contains(world::Item{3,1}),"full reset omission hides prior entity");
    check(current->world().remembered(world::Node{77,1})==world::Entity{world::Node{77,3}},"hidden generation fence preserved");
    check(!current->world().table<wire::Vitals>().find(world::Player{7,1}) && !current->world().table<wire::Gear>().find(world::Player{7,1}) &&
        !current->world().table<wire::CastBar>().find(world::Player{7,1}) && !current->world().table<wire::Look>().find(world::Player{7,1}),"full component absence clears all optionals");
    check(pinned->world().table<wire::Vitals>().find(world::Player{7,1})->hp()==90 && pinned->world().contains(world::Item{3,1}),"old pinned view remains immutable");
    const auto commit=wire::decode_intents((**value).application_commit);
    check(commit && std::get<wire::ResetCommit>(*commit).certificate()==certificate,"control commit certifies exact baseline");
    check(receive(core,*wire::ResetClose::build({certificate})),"lost commit duplicate close accepted");
    check(!core.publish(128*1024*1024)->has_value() && core.latest()==current,"duplicate close creates no second publication");
    check(core.take_reset_commit()==std::optional{(**value).application_commit} && !core.take_reset_commit(),"one bounded idempotent commit retry");
    transport::Received delta{};delta.unreliable=transport::Unreliable{11,{bytes(*wire::EntityReplace::build({row(wire::PlayerId{7,1},6,true)}))}};
    delta.reliable={bytes(*wire::TickClose::build({88,2,11,2,1,1}))};
    check(core.receive(delta,{440000}).has_value() && core.publish(128*1024*1024)->has_value(),"ordinary explicit complete replacement admitted");
    delta.unreliable=transport::Unreliable{12,{bytes(*wire::Entity::build({wire::PlayerId{7,1},*wire::Transform::build({8,0,0}),{},{},{},{}}))}};
    delta.reliable={bytes(*wire::TickClose::build({88,2,12,2,1,1}))};
    check(core.receive(delta,{480000}).has_value() && core.publish(128*1024*1024)->has_value(),"ordinary partial delta admitted");
    check(core.latest()->world().table<wire::Vitals>().find(world::Player{7,1})->hp()==90,"ordinary omission still retains components");
    delta.unreliable=transport::Unreliable{13,{bytes(*wire::EntityReplace::build({row(wire::PlayerId{7,1},9)}))}};
    delta.reliable={bytes(*wire::TickClose::build({88,2,13,2,1,1}))};
    check(core.receive(delta,{520000}).has_value() && core.publish(128*1024*1024)->has_value(),"ordinary replacement removal published");
    check(!core.latest()->world().table<wire::Vitals>().find(world::Player{7,1}),"ordinary explicit replacement clears optional component");

    auto stale=prior();const auto before=stale.latest();
    check(stale.replace_lease(88,2,42,{7,1},{400000}).has_value(),"stale fixture lease");
    check(receive(stale,begin(cert(2,42,1,2,1))),"stale fixture begin");
    check(receive(stale,*wire::ResetPart::build({cert(2,42,1,2,1),0,{row(wire::PlayerId{7,1},5),row(wire::NodeId{77,2},1)}})),"stale generation staged privately");
    check(receive(stale,*wire::ResetClose::build({cert(2,42,1,2,1)})),"stale fixture close");
    auto refused=stale.publish(128*1024*1024);
    check(!refused && refused.error()==client::DomainError::world && stale.latest()==before,"older hidden generation prevents whole reset");
    check(!receive(stale,begin(cert(2,43,1,2,1))) && stale.latest()==before,"wrong lease cannot replace checkpoint");
    check(receive(stale,*wire::ResetUnavailable::build({88,2,42,wire::ResetFailure::history}))==false && stale.phase()==client::DomainPhase::unavailable && stale.latest()==before,"missing history explicitly unavailable preserves checkpoint");

    auto timeout=prior();const auto timeout_before=timeout.latest();
    check(timeout.replace_lease(88,2,42,{7,1},{400000}).has_value(),"deadline fixture lease");
    check(!timeout.advance_reset({30400001}) && timeout.unavailable_reason()==wire::ResetFailure::deadline && timeout.latest()==timeout_before,"deadline preserves coherent old checkpoint");
    for (bool decoded:{false,true}) {
        auto limited=prior();client::ResetLimits limits;
        if(decoded)limits.decoded_bytes=1;else limits.encoded_bytes=1;
        check(limited.replace_lease(88,2,42,{7,1},{400000},limits).has_value(),"capacity fixture lease");
        const auto old=limited.latest();
        check(!receive(limited,begin(cert())) && limited.phase()==client::DomainPhase::unavailable && limited.unavailable_reason()==wire::ResetFailure::capacity && limited.latest()==old,"staging capacity is observable unavailable");
    }
    auto future=prior();check(future.replace_lease(88,2,42,{7,1},{400000}).has_value(),"future cursor fixture lease");
    check(!receive(future,begin(cert(2,42,2,2,2,2))) && future.latest()->tick().value==10,"future unadmitted frontier cannot certify reset");
    check(!wire::ResetBegin::build({certificate,*wire::MotionBaseline::build({89,2,{7,1},10,0,5,0,0,0,0,0,true,wire::MotionMode::free,0,"village",2,128,0,40000})}),"generated cross-identity relation enforced");
    check(!wire::ResetPart::build({certificate,2,{row(wire::PlayerId{7,1},5)}}),"generated index count relation enforced");
    auto network=prior();
    check(network.replace_lease(88,2,42,{7,1},{400000}).has_value(),"encrypted fixture lease");
    transport::SessionKeys keys{};
    for(std::size_t i=0;i<transport::kKeySize;++i){keys.client_to_server[i]=i+1;keys.server_to_client[i]=i+65;}
    auto client_seal=transport::session_seal(transport::Role::client,keys);
    auto server_seal=transport::session_seal(transport::Role::server,keys);
    const auto config=transport::default_config(wire::schema_hash);
    auto client_endpoint=transport::Endpoint::create(transport::Role::client,config,std::move(client_seal.opener),std::move(client_seal.sealer),400000);
    auto server_endpoint=transport::Endpoint::create(transport::Role::server,config,std::move(server_seal.opener),std::move(server_seal.sealer),400000);
    check(client_endpoint.has_value() && server_endpoint.has_value(),"actual encrypted Endpoints created");
    for(const auto& message:std::vector<std::vector<std::uint8_t>>{bytes(begin(certificate)),bytes(quest),
        bytes(*wire::ResetPart::build({certificate,0,{row(wire::PlayerId{7,1},5)}})),bytes(part1),bytes(*wire::ResetClose::build({certificate}))})
        check(server_endpoint->send(message).has_value(),"reset admitted by actual Sender");
    netsim::Simulator sim(netsim::kBadWifi,36320261006ULL);
    std::size_t publications=0;bool committed=false;std::uint64_t completed_at=0;std::size_t delivered=0;
    for(std::uint64_t now=400000;now<=10400000 && !committed;now+=40000){
        auto outgoing=server_endpoint->flush(now);check(outgoing.has_value(),"one server flush per tick");
        std::size_t sent=0;
        for(auto& packet:outgoing->datagrams){sent+=packet.size();sim.send(netsim::Direction::kAToB,std::move(packet),now);}
        check(sent<=4800,"actual total per-tick budget preserved");
        for(const auto& delivery:sim.poll(netsim::Direction::kAToB,now)){
            auto decoded=client_endpoint->receive(delivery.packet,now);
            if(!decoded)continue;
            ++delivered;check(network.receive(*decoded,{static_cast<std::int64_t>(now)}).has_value(),"actual plaintext enters same Assembler");
        }
        auto publication=network.publish(128*1024*1024);check(publication.has_value(),"actual reset publication attempt valid");
        if(publication->has_value()){
            ++publications;completed_at=now;
            check(client_endpoint->send((**publication).application_commit).has_value(),"actual reset certificate control admitted");
        }
        auto reply=client_endpoint->flush(now);check(reply.has_value(),"one client flush per tick");
        for(auto& packet:reply->datagrams)sim.send(netsim::Direction::kBToA,std::move(packet),now);
        for(const auto& delivery:sim.poll(netsim::Direction::kBToA,now)){
            auto decoded=server_endpoint->receive(delivery.packet,now);
            if(!decoded)continue;
            for(const auto& message:decoded->reliable){
                const auto control=wire::decode_intents(message);
                check(control && std::holds_alternative<wire::ResetCommit>(*control) && std::get<wire::ResetCommit>(*control).certificate()==certificate,"actual peer receives exact reset control");
                committed=true;
            }
        }
    }
    check(committed && delivered>0 && publications==1 && network.latest()->events().event_end==2 && network.latest()->events().changes.size()==1,"bad_wifi encrypted reset publishes once and commits actual prefix");
    std::cout<<"reset Endpoint bad_wifi seed=36320261006 publications="<<publications<<" delivered="<<delivered<<" completed_at_us="<<completed_at<<'\n';
    const auto result=test::check_finish();
    if (!result) std::cout<<"client reset literal tests passed tick=10 prefix=2 optional_clear=4 lost_commit_publications=1\n";
    return result;
}
