// Code generated by wiregen from shared/wire/testdata/probe.wire. DO NOT EDIT.

package probe

import (
	"fmt"

	"github.com/devarminas/marque/server/internal/wire/codec"
)

// SchemaHash identifies the schema this file was generated from.
const SchemaHash uint64 = 0x939f35c2cdc94ad8

type Message interface {
	MessageID() uint32
	Channel() codec.Channel
	Append(dst []byte) ([]byte, error)
	String() string
}

// StateMsg is a message sent on the state channel.
type StateMsg interface {
	Message
	stateMsg()
}

// EventsMsg is a message sent on the events channel.
type EventsMsg interface {
	Message
	eventsMsg()
}

// InputMsg is a message sent on the input channel.
type InputMsg interface {
	Message
	inputMsg()
}

// IntentsMsg is a message sent on the intents channel.
type IntentsMsg interface {
	Message
	intentsMsg()
}

var quantCoord = codec.Quant{Min: -10, Max: 10, PerUnit: 4, Steps: 80, Width: 1}

// PlayerId pairs a slot index with the generation that slot had when the
// entity was created, so a reused index never names the old entity.
type PlayerId struct {
	Index uint32
	Gen   uint32
}

func (v PlayerId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodePlayerId(r *codec.Reader) (v PlayerId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v PlayerId) String() string { return fmt.Sprintf("PlayerId(%d/%d)", v.Index, v.Gen) }

// NpcId pairs a slot index with the generation that slot had when the
// entity was created, so a reused index never names the old entity.
type NpcId struct {
	Index uint32
	Gen   uint32
}

func (v NpcId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeNpcId(r *codec.Reader) (v NpcId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v NpcId) String() string { return fmt.Sprintf("NpcId(%d/%d)", v.Index, v.Gen) }

type Color uint32

const (
	ColorRed   Color = 0
	ColorGreen Color = 7
	ColorBlue  Color = 300
)

func (v Color) String() string {
	switch v {
	case ColorRed:
		return "red"
	case ColorGreen:
		return "green"
	case ColorBlue:
		return "blue"
	}
	return fmt.Sprintf("Color(%d)", uint32(v))
}

func (v Color) valid() bool {
	switch v {
	case ColorRed, ColorGreen, ColorBlue:
		return true
	}
	return false
}

func (v Color) encode(w *codec.Writer) {
	if !v.valid() {
		w.Fail(codec.ErrBadEnum)
		return
	}
	w.Varint(uint32(v))
}

func decodeColor(r *codec.Reader) Color {
	v := Color(r.Varint())
	if r.Err() == nil && !v.valid() {
		r.Fail(codec.ErrBadEnum)
	}
	return v
}

type Pair struct {
	Who    NpcId
	Weight float32
}

func (v Pair) encode(w *codec.Writer) {
	v.Who.encode(w)
	w.F32(v.Weight)
}

func decodePair(r *codec.Reader) (v Pair) {
	v.Who = decodeNpcId(r)
	v.Weight = r.F32()
	return v
}

func (v Pair) String() string {
	return fmt.Sprintf("Pair{who:%v weight:%v}", v.Who, v.Weight)
}

type Probe struct {
	Label  string
	Ratio  float32
	Pairs  []Pair
	Flag   bool
	Color  Color
	At     float64
	Shorts []uint16
	AU8    uint8
	AU16   uint16
	AU32   uint32
	AU64   uint64
	AI8    int8
	AI16   int16
	AI32   int32
	AI64   int64
	Owner  PlayerId
}

func (v Probe) encode(w *codec.Writer) {
	w.String(v.Label, 8)
	w.F32(v.Ratio)
	w.Count(len(v.Pairs), 3)
	for _, e := range v.Pairs {
		e.encode(w)
	}
	w.Bool(v.Flag)
	v.Color.encode(w)
	w.Quant(v.At, quantCoord)
	w.Count(len(v.Shorts), 2)
	for _, e := range v.Shorts {
		w.U16(e)
	}
	w.U8(v.AU8)
	w.U16(v.AU16)
	w.U32(v.AU32)
	w.U64(v.AU64)
	w.U8(uint8(v.AI8))
	w.U16(uint16(v.AI16))
	w.U32(uint32(v.AI32))
	w.U64(uint64(v.AI64))
	v.Owner.encode(w)
}

func decodeProbe(r *codec.Reader) (v Probe) {
	v.Label = r.String(8)
	v.Ratio = r.F32()
	if n := r.Count(3, 6); n > 0 {
		v.Pairs = make([]Pair, n)
		for i := range v.Pairs {
			v.Pairs[i] = decodePair(r)
		}
	}
	v.Flag = r.Bool()
	v.Color = decodeColor(r)
	v.At = r.Quant(quantCoord)
	if n := r.Count(2, 2); n > 0 {
		v.Shorts = make([]uint16, n)
		for i := range v.Shorts {
			v.Shorts[i] = r.U16()
		}
	}
	v.AU8 = r.U8()
	v.AU16 = r.U16()
	v.AU32 = r.U32()
	v.AU64 = r.U64()
	v.AI8 = int8(r.U8())
	v.AI16 = int16(r.U16())
	v.AI32 = int32(r.U32())
	v.AI64 = int64(r.U64())
	v.Owner = decodePlayerId(r)
	return v
}

func (v Probe) String() string {
	return fmt.Sprintf("probe{label:%q ratio:%v pairs:%v flag:%v color:%v at:%v shorts:%v a_u8:%v a_u16:%v a_u32:%v a_u64:%v a_i8:%v a_i16:%v a_i32:%v a_i64:%v owner:%v}", v.Label, v.Ratio, v.Pairs, v.Flag, v.Color, v.At, v.Shorts, v.AU8, v.AU16, v.AU32, v.AU64, v.AI8, v.AI16, v.AI32, v.AI64, v.Owner)
}

func (Probe) MessageID() uint32 { return 1 }

func (Probe) Channel() codec.Channel { return codec.ChannelEvents }

func (Probe) eventsMsg() {}

func (v Probe) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(1)
	v.encode(&w)
	return w.Result()
}

type Ping struct {
	Nonce uint8
}

func (v Ping) encode(w *codec.Writer) {
	w.U8(v.Nonce)
}

func decodePing(r *codec.Reader) (v Ping) {
	v.Nonce = r.U8()
	return v
}

func (v Ping) String() string {
	return fmt.Sprintf("ping{nonce:%v}", v.Nonce)
}

func (Ping) MessageID() uint32 { return 2 }

func (Ping) Channel() codec.Channel { return codec.ChannelIntents }

func (Ping) intentsMsg() {}

func (v Ping) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(2)
	v.encode(&w)
	return w.Result()
}

type Crowd struct {
	Pairs []Pair
}

func (v Crowd) encode(w *codec.Writer) {
	w.Count(len(v.Pairs), 65535)
	for _, e := range v.Pairs {
		e.encode(w)
	}
}

func decodeCrowd(r *codec.Reader) (v Crowd) {
	if n := r.Count(65535, 6); n > 0 {
		v.Pairs = make([]Pair, n)
		for i := range v.Pairs {
			v.Pairs[i] = decodePair(r)
		}
	}
	return v
}

func (v Crowd) String() string {
	return fmt.Sprintf("crowd{pairs:%v}", v.Pairs)
}

func (Crowd) MessageID() uint32 { return 3 }

func (Crowd) Channel() codec.Channel { return codec.ChannelEvents }

func (Crowd) eventsMsg() {}

func (v Crowd) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(3)
	v.encode(&w)
	return w.Result()
}

// DecodeNextState reads one state message and leaves r after it. An id from
// another channel fails with codec.ErrUnknownMessage.
func DecodeNextState(r *codec.Reader) (StateMsg, error) {
	var m StateMsg
	switch r.Varint() {
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

// DecodeState decodes exactly one state message; any byte left over is an error.
func DecodeState(b []byte) (StateMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextState(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

// DecodeNextEvents reads one events message and leaves r after it. An id from
// another channel fails with codec.ErrUnknownMessage.
func DecodeNextEvents(r *codec.Reader) (EventsMsg, error) {
	var m EventsMsg
	switch r.Varint() {
	case 1:
		m = decodeProbe(r)
	case 3:
		m = decodeCrowd(r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

// DecodeEvents decodes exactly one events message; any byte left over is an error.
func DecodeEvents(b []byte) (EventsMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextEvents(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

// DecodeNextInput reads one input message and leaves r after it. An id from
// another channel fails with codec.ErrUnknownMessage.
func DecodeNextInput(r *codec.Reader) (InputMsg, error) {
	var m InputMsg
	switch r.Varint() {
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

// DecodeInput decodes exactly one input message; any byte left over is an error.
func DecodeInput(b []byte) (InputMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextInput(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

// DecodeNextIntents reads one intents message and leaves r after it. An id from
// another channel fails with codec.ErrUnknownMessage.
func DecodeNextIntents(r *codec.Reader) (IntentsMsg, error) {
	var m IntentsMsg
	switch r.Varint() {
	case 2:
		m = decodePing(r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

// DecodeIntents decodes exactly one intents message; any byte left over is an error.
func DecodeIntents(b []byte) (IntentsMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextIntents(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}
