// Code generated by wiregen from shared/wire/testdata/probe.wire. DO NOT EDIT.

package probe

import (
	"fmt"
	"slices"
	"strconv"

	"github.com/devarminas/marque/server/internal/wire/codec"
)

const SchemaHash uint64 = 0xf06ba111555b7fc8

type Message interface {
	MessageID() uint32
	Channel() codec.Channel
	Append(dst []byte) ([]byte, error)
	String() string
}

type StateMsg interface {
	Message
	stateMsg()
}

type EventsMsg interface {
	Message
	eventsMsg()
}

type InputMsg interface {
	Message
	inputMsg()
}

type IntentsMsg interface {
	Message
	intentsMsg()
}

var quantCoord = codec.Quant{Min: -10, Max: 10, PerUnit: 4, Steps: 80, Width: 1}

type PlayerId struct {
	Index uint32
	Gen   uint32
}

func (v PlayerId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodePlayerId(r *codec.Reader) (v PlayerId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v PlayerId) appendText(b []byte) []byte {
	b = append(b, "PlayerId("...)
	b = strconv.AppendUint(b, uint64(v.Index), 10)
	b = append(b, '/')
	b = strconv.AppendUint(b, uint64(v.Gen), 10)
	return append(b, ')')
}

func (v PlayerId) String() string { return string(v.appendText(nil)) }

type NpcId struct {
	Index uint32
	Gen   uint32
}

func (v NpcId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeNpcId(r *codec.Reader) (v NpcId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v NpcId) appendText(b []byte) []byte {
	b = append(b, "NpcId("...)
	b = strconv.AppendUint(b, uint64(v.Index), 10)
	b = append(b, '/')
	b = strconv.AppendUint(b, uint64(v.Gen), 10)
	return append(b, ')')
}

func (v NpcId) String() string { return string(v.appendText(nil)) }

type ItemId struct {
	Index uint32
	Gen   uint32
}

func (v ItemId) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decodeItemId(r *codec.Reader) (v ItemId) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v ItemId) appendText(b []byte) []byte {
	b = append(b, "ItemId("...)
	b = strconv.AppendUint(b, uint64(v.Index), 10)
	b = append(b, '/')
	b = strconv.AppendUint(b, uint64(v.Gen), 10)
	return append(b, ')')
}

func (v ItemId) String() string { return string(v.appendText(nil)) }

type Color uint32

const (
	ColorRed   Color = 0
	ColorGreen Color = 7
	ColorBlue  Color = 300
)

func (v Color) String() string {
	switch v {
	case ColorRed:
		return "red"
	case ColorGreen:
		return "green"
	case ColorBlue:
		return "blue"
	}
	return fmt.Sprintf("Color(%d)", uint32(v))
}

func (v Color) valid() bool {
	switch v {
	case ColorRed, ColorGreen, ColorBlue:
		return true
	}
	return false
}

func (v Color) encode(w *codec.Writer) {
	if !v.valid() {
		w.Fail(codec.ErrBadEnum)
		return
	}
	w.Varint(uint32(v))
}

func decodeColor(r *codec.Reader) Color {
	v := Color(r.Varint())
	if r.Err() == nil && !v.valid() {
		r.Fail(codec.ErrBadEnum)
	}
	return v
}

type Option uint32

const (
	OptionAcceptQuest Option = 1
	OptionTurnInQuest Option = 2
	OptionStopTalking Option = 3
	OptionTrade       Option = 4
)

func (v Option) String() string {
	switch v {
	case OptionAcceptQuest:
		return "accept_quest"
	case OptionTurnInQuest:
		return "turn_in_quest"
	case OptionStopTalking:
		return "stop_talking"
	case OptionTrade:
		return "trade"
	}
	return fmt.Sprintf("Option(%d)", uint32(v))
}

func (v Option) valid() bool {
	switch v {
	case OptionAcceptQuest, OptionTurnInQuest, OptionStopTalking, OptionTrade:
		return true
	}
	return false
}

func (v Option) encode(w *codec.Writer) {
	if !v.valid() {
		w.Fail(codec.ErrBadEnum)
		return
	}
	w.Varint(uint32(v))
}

func decodeOption(r *codec.Reader) Option {
	v := Option(r.Varint())
	if r.Err() == nil && !v.valid() {
		r.Fail(codec.ErrBadEnum)
	}
	return v
}

type Who interface {
	isWho()
}

func (PlayerId) isWho() {}

func (NpcId) isWho() {}

func encodeWho(w *codec.Writer, v Who) {
	switch v := v.(type) {
	case PlayerId:
		w.Varint(1)
		v.encode(w)
	case NpcId:
		w.Varint(7)
		v.encode(w)
	default:
		w.Fail(codec.ErrBadEnum)
	}
}

func decodeWho(r *codec.Reader) Who {
	switch r.Varint() {
	case 1:
		return decodePlayerId(r)
	case 7:
		return decodeNpcId(r)
	}
	r.Fail(codec.ErrBadEnum)
	return nil
}

func appendWhoText(b []byte, v Who) []byte {
	switch v := v.(type) {
	case PlayerId:
		return v.appendText(b)
	case NpcId:
		return v.appendText(b)
	}
	return append(b, "Who(nil)"...)
}

type PairFields struct {
	Who    NpcId
	Weight float32
}

type Pair struct {
	f PairFields
}

func (f PairFields) Build() (Pair, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Pair{}, err
	}
	return Pair{f}, nil
}

func (v Pair) Who() NpcId { return v.f.Who }

func (v Pair) Weight() float32 { return v.f.Weight }

func (f PairFields) encode(w *codec.Writer) {
	f.Who.encode(w)
	w.F32(f.Weight)
}

func decodePair(r *codec.Reader) Pair {
	var f PairFields
	f.Who = decodeNpcId(r)
	f.Weight = r.F32()
	return Pair{f}
}

func (f PairFields) appendText(b []byte) []byte {
	b = append(b, "Pair{who:"...)
	b = f.Who.appendText(b)
	b = append(b, " weight:"...)
	b = strconv.AppendFloat(b, float64(f.Weight), 'g', -1, 32)
	return append(b, '}')
}

func (v Pair) String() string { return string(v.f.appendText(nil)) }

type BagSlotFields struct {
	Slot uint8
	Item ItemId
}

type BagSlot struct {
	f BagSlotFields
}

func (f BagSlotFields) Build() (BagSlot, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return BagSlot{}, err
	}
	return BagSlot{f}, nil
}

func (v BagSlot) Slot() uint8 { return v.f.Slot }

func (v BagSlot) Item() ItemId { return v.f.Item }

func (f BagSlotFields) encode(w *codec.Writer) {
	w.U8(f.Slot)
	if w.Err() == nil && !(f.Slot <= 39) {
		w.Fail(codec.ErrRule)
	}
	f.Item.encode(w)
}

func decodeBagSlot(r *codec.Reader) BagSlot {
	var f BagSlotFields
	f.Slot = r.U8()
	if r.Err() == nil && !(f.Slot <= 39) {
		r.Fail(codec.ErrRule)
	}
	f.Item = decodeItemId(r)
	return BagSlot{f}
}

func (f BagSlotFields) appendText(b []byte) []byte {
	b = append(b, "BagSlot{slot:"...)
	b = strconv.AppendUint(b, uint64(f.Slot), 10)
	b = append(b, " item:"...)
	b = f.Item.appendText(b)
	return append(b, '}')
}

func (v BagSlot) String() string { return string(v.f.appendText(nil)) }

type OfferFields struct {
	Owner PlayerId
	Item  ItemId
}

type Offer struct {
	f OfferFields
}

func (f OfferFields) Build() (Offer, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Offer{}, err
	}
	return Offer{f}, nil
}

func (v Offer) Owner() PlayerId { return v.f.Owner }

func (v Offer) Item() ItemId { return v.f.Item }

func (f OfferFields) encode(w *codec.Writer) {
	f.Owner.encode(w)
	f.Item.encode(w)
}

func decodeOffer(r *codec.Reader) Offer {
	var f OfferFields
	f.Owner = decodePlayerId(r)
	f.Item = decodeItemId(r)
	return Offer{f}
}

func (f OfferFields) appendText(b []byte) []byte {
	b = append(b, "Offer{owner:"...)
	b = f.Owner.appendText(b)
	b = append(b, " item:"...)
	b = f.Item.appendText(b)
	return append(b, '}')
}

func (v Offer) String() string { return string(v.f.appendText(nil)) }

type ProbeFields struct {
	Label  string
	Ratio  float32
	Pairs  []Pair
	Flag   bool
	Color  Color
	At     float64
	Shorts []uint16
	AU8    uint8
	AU16   uint16
	AU32   uint32
	AU64   uint64
	AI8    int8
	AI16   int16
	AI32   int32
	AI64   int64
	Owner  PlayerId
}

type Probe struct {
	f ProbeFields
}

func (f ProbeFields) Build() (Probe, error) {
	f.Pairs = codec.Clone(f.Pairs)
	f.Shorts = codec.Clone(f.Shorts)
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Probe{}, err
	}
	return Probe{f}, nil
}

func (v Probe) Label() string { return v.f.Label }

func (v Probe) Ratio() float32 { return v.f.Ratio }

func (v Probe) Pairs() codec.List[Pair] { return codec.ListOf(v.f.Pairs) }

func (v Probe) Flag() bool { return v.f.Flag }

func (v Probe) Color() Color { return v.f.Color }

func (v Probe) At() float64 { return v.f.At }

func (v Probe) Shorts() codec.List[uint16] { return codec.ListOf(v.f.Shorts) }

func (v Probe) AU8() uint8 { return v.f.AU8 }

func (v Probe) AU16() uint16 { return v.f.AU16 }

func (v Probe) AU32() uint32 { return v.f.AU32 }

func (v Probe) AU64() uint64 { return v.f.AU64 }

func (v Probe) AI8() int8 { return v.f.AI8 }

func (v Probe) AI16() int16 { return v.f.AI16 }

func (v Probe) AI32() int32 { return v.f.AI32 }

func (v Probe) AI64() int64 { return v.f.AI64 }

func (v Probe) Owner() PlayerId { return v.f.Owner }

func (f ProbeFields) encode(w *codec.Writer) {
	w.String(f.Label, 8)
	w.F32(f.Ratio)
	w.Count(len(f.Pairs), 3)
	for _, e := range f.Pairs {
		e.f.encode(w)
	}
	w.Bool(f.Flag)
	f.Color.encode(w)
	w.Quant(f.At, quantCoord)
	w.Count(len(f.Shorts), 2)
	for _, e := range f.Shorts {
		w.U16(e)
	}
	w.U8(f.AU8)
	w.U16(f.AU16)
	w.U32(f.AU32)
	w.U64(f.AU64)
	w.U8(uint8(f.AI8))
	w.U16(uint16(f.AI16))
	w.U32(uint32(f.AI32))
	w.U64(uint64(f.AI64))
	f.Owner.encode(w)
}

func decodeProbe(r *codec.Reader) Probe {
	var f ProbeFields
	f.Label = r.String(8)
	f.Ratio = r.F32()
	if n := r.Count(3, 6); n > 0 {
		f.Pairs = make([]Pair, n)
		for i := range f.Pairs {
			f.Pairs[i] = decodePair(r)
		}
	}
	f.Flag = r.Bool()
	f.Color = decodeColor(r)
	f.At = r.Quant(quantCoord)
	if n := r.Count(2, 2); n > 0 {
		f.Shorts = make([]uint16, n)
		for i := range f.Shorts {
			f.Shorts[i] = r.U16()
		}
	}
	f.AU8 = r.U8()
	f.AU16 = r.U16()
	f.AU32 = r.U32()
	f.AU64 = r.U64()
	f.AI8 = int8(r.U8())
	f.AI16 = int16(r.U16())
	f.AI32 = int32(r.U32())
	f.AI64 = int64(r.U64())
	f.Owner = decodePlayerId(r)
	return Probe{f}
}

func (f ProbeFields) appendText(b []byte) []byte {
	b = append(b, "probe{label:"...)
	b = strconv.AppendQuoteToASCII(b, f.Label)
	b = append(b, " ratio:"...)
	b = strconv.AppendFloat(b, float64(f.Ratio), 'g', -1, 32)
	b = append(b, " pairs:"...)
	b = append(b, '[')
	for i, e := range f.Pairs {
		if i > 0 {
			b = append(b, ' ')
		}
		b = e.f.appendText(b)
	}
	b = append(b, ']')
	b = append(b, " flag:"...)
	b = strconv.AppendBool(b, f.Flag)
	b = append(b, " color:"...)
	b = append(b, f.Color.String()...)
	b = append(b, " at:"...)
	b = strconv.AppendFloat(b, f.At, 'g', -1, 64)
	b = append(b, " shorts:"...)
	b = append(b, '[')
	for i, e := range f.Shorts {
		if i > 0 {
			b = append(b, ' ')
		}
		b = strconv.AppendUint(b, uint64(e), 10)
	}
	b = append(b, ']')
	b = append(b, " a_u8:"...)
	b = strconv.AppendUint(b, uint64(f.AU8), 10)
	b = append(b, " a_u16:"...)
	b = strconv.AppendUint(b, uint64(f.AU16), 10)
	b = append(b, " a_u32:"...)
	b = strconv.AppendUint(b, uint64(f.AU32), 10)
	b = append(b, " a_u64:"...)
	b = strconv.AppendUint(b, uint64(f.AU64), 10)
	b = append(b, " a_i8:"...)
	b = strconv.AppendInt(b, int64(f.AI8), 10)
	b = append(b, " a_i16:"...)
	b = strconv.AppendInt(b, int64(f.AI16), 10)
	b = append(b, " a_i32:"...)
	b = strconv.AppendInt(b, int64(f.AI32), 10)
	b = append(b, " a_i64:"...)
	b = strconv.AppendInt(b, int64(f.AI64), 10)
	b = append(b, " owner:"...)
	b = f.Owner.appendText(b)
	return append(b, '}')
}

func (v Probe) String() string { return string(v.f.appendText(nil)) }

func (Probe) MessageID() uint32 { return 1 }

func (Probe) Channel() codec.Channel { return codec.ChannelEvents }

func (Probe) eventsMsg() {}

func (v Probe) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(1)
	v.f.encode(&w)
	return w.Result()
}

type PingFields struct {
	Nonce uint8
}

type Ping struct {
	f PingFields
}

func (f PingFields) Build() (Ping, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Ping{}, err
	}
	return Ping{f}, nil
}

func (v Ping) Nonce() uint8 { return v.f.Nonce }

func (f PingFields) encode(w *codec.Writer) {
	w.U8(f.Nonce)
}

func decodePing(r *codec.Reader) Ping {
	var f PingFields
	f.Nonce = r.U8()
	return Ping{f}
}

func (f PingFields) appendText(b []byte) []byte {
	b = append(b, "ping{nonce:"...)
	b = strconv.AppendUint(b, uint64(f.Nonce), 10)
	return append(b, '}')
}

func (v Ping) String() string { return string(v.f.appendText(nil)) }

func (Ping) MessageID() uint32 { return 2 }

func (Ping) Channel() codec.Channel { return codec.ChannelIntents }

func (Ping) intentsMsg() {}

func (v Ping) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(2)
	v.f.encode(&w)
	return w.Result()
}

type CrowdFields struct {
	Pairs []Pair
}

type Crowd struct {
	f CrowdFields
}

func (f CrowdFields) Build() (Crowd, error) {
	f.Pairs = codec.Clone(f.Pairs)
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Crowd{}, err
	}
	return Crowd{f}, nil
}

func (v Crowd) Pairs() codec.List[Pair] { return codec.ListOf(v.f.Pairs) }

func (f CrowdFields) encode(w *codec.Writer) {
	w.Count(len(f.Pairs), 65535)
	for _, e := range f.Pairs {
		e.f.encode(w)
	}
}

func decodeCrowd(r *codec.Reader) Crowd {
	var f CrowdFields
	if n := r.Count(65535, 6); n > 0 {
		f.Pairs = make([]Pair, n)
		for i := range f.Pairs {
			f.Pairs[i] = decodePair(r)
		}
	}
	return Crowd{f}
}

func (f CrowdFields) appendText(b []byte) []byte {
	b = append(b, "crowd{pairs:"...)
	b = append(b, '[')
	for i, e := range f.Pairs {
		if i > 0 {
			b = append(b, ' ')
		}
		b = e.f.appendText(b)
	}
	b = append(b, ']')
	return append(b, '}')
}

func (v Crowd) String() string { return string(v.f.appendText(nil)) }

func (Crowd) MessageID() uint32 { return 3 }

func (Crowd) Channel() codec.Channel { return codec.ChannelEvents }

func (Crowd) eventsMsg() {}

func (v Crowd) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(3)
	v.f.encode(&w)
	return w.Result()
}

type PartyFields struct {
	Leader  PlayerId
	Members []PlayerId
}

type Party struct {
	f PartyFields
}

func (f PartyFields) Build() (Party, error) {
	f.Members = codec.Clone(f.Members)
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Party{}, err
	}
	return Party{f}, nil
}

func (v Party) Leader() PlayerId { return v.f.Leader }

func (v Party) Members() codec.List[PlayerId] { return codec.ListOf(v.f.Members) }

func (f PartyFields) encode(w *codec.Writer) {
	f.Leader.encode(w)
	w.Count(len(f.Members), 5)
	for _, e := range f.Members {
		e.encode(w)
	}
	if w.Err() == nil && !codec.Unique(len(f.Members), func(i, j int) bool { return f.Members[i] == f.Members[j] }) {
		w.Fail(codec.ErrRule)
	}
	if w.Err() == nil && !slices.ContainsFunc(f.Members, func(e PlayerId) bool { return e == f.Leader }) {
		w.Fail(codec.ErrRule)
	}
}

func decodeParty(r *codec.Reader) Party {
	var f PartyFields
	f.Leader = decodePlayerId(r)
	if n := r.Count(5, 2); n > 0 {
		f.Members = make([]PlayerId, n)
		for i := range f.Members {
			f.Members[i] = decodePlayerId(r)
		}
	}
	if r.Err() == nil && !codec.Unique(len(f.Members), func(i, j int) bool { return f.Members[i] == f.Members[j] }) {
		r.Fail(codec.ErrRule)
	}
	if r.Err() == nil && !slices.ContainsFunc(f.Members, func(e PlayerId) bool { return e == f.Leader }) {
		r.Fail(codec.ErrRule)
	}
	return Party{f}
}

func (f PartyFields) appendText(b []byte) []byte {
	b = append(b, "party{leader:"...)
	b = f.Leader.appendText(b)
	b = append(b, " members:"...)
	b = append(b, '[')
	for i, e := range f.Members {
		if i > 0 {
			b = append(b, ' ')
		}
		b = e.appendText(b)
	}
	b = append(b, ']')
	return append(b, '}')
}

func (v Party) String() string { return string(v.f.appendText(nil)) }

func (Party) MessageID() uint32 { return 4 }

func (Party) Channel() codec.Channel { return codec.ChannelEvents }

func (Party) eventsMsg() {}

func (v Party) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(4)
	v.f.encode(&w)
	return w.Result()
}

type InventoryFields struct {
	Size  uint8
	Slots []BagSlot
}

type Inventory struct {
	f InventoryFields
}

func (f InventoryFields) Build() (Inventory, error) {
	f.Slots = codec.Clone(f.Slots)
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Inventory{}, err
	}
	return Inventory{f}, nil
}

func (v Inventory) Size() uint8 { return v.f.Size }

func (v Inventory) Slots() codec.List[BagSlot] { return codec.ListOf(v.f.Slots) }

func (f InventoryFields) encode(w *codec.Writer) {
	w.U8(f.Size)
	if w.Err() == nil && !(f.Size >= 1 && f.Size <= 40) {
		w.Fail(codec.ErrRule)
	}
	w.Count(len(f.Slots), 40)
	for _, e := range f.Slots {
		e.f.encode(w)
	}
	if w.Err() == nil && !codec.Unique(len(f.Slots), func(i, j int) bool { return f.Slots[i].f.Slot == f.Slots[j].f.Slot }) {
		w.Fail(codec.ErrRule)
	}
	if w.Err() == nil && slices.ContainsFunc(f.Slots, func(e BagSlot) bool { return !(e.f.Slot < f.Size) }) {
		w.Fail(codec.ErrRule)
	}
}

func decodeInventory(r *codec.Reader) Inventory {
	var f InventoryFields
	f.Size = r.U8()
	if r.Err() == nil && !(f.Size >= 1 && f.Size <= 40) {
		r.Fail(codec.ErrRule)
	}
	if n := r.Count(40, 3); n > 0 {
		f.Slots = make([]BagSlot, n)
		for i := range f.Slots {
			f.Slots[i] = decodeBagSlot(r)
		}
	}
	if r.Err() == nil && !codec.Unique(len(f.Slots), func(i, j int) bool { return f.Slots[i].f.Slot == f.Slots[j].f.Slot }) {
		r.Fail(codec.ErrRule)
	}
	if r.Err() == nil && slices.ContainsFunc(f.Slots, func(e BagSlot) bool { return !(e.f.Slot < f.Size) }) {
		r.Fail(codec.ErrRule)
	}
	return Inventory{f}
}

func (f InventoryFields) appendText(b []byte) []byte {
	b = append(b, "inventory{size:"...)
	b = strconv.AppendUint(b, uint64(f.Size), 10)
	b = append(b, " slots:"...)
	b = append(b, '[')
	for i, e := range f.Slots {
		if i > 0 {
			b = append(b, ' ')
		}
		b = e.f.appendText(b)
	}
	b = append(b, ']')
	return append(b, '}')
}

func (v Inventory) String() string { return string(v.f.appendText(nil)) }

func (Inventory) MessageID() uint32 { return 5 }

func (Inventory) Channel() codec.Channel { return codec.ChannelEvents }

func (Inventory) eventsMsg() {}

func (v Inventory) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(5)
	v.f.encode(&w)
	return w.Result()
}

type DialogFields struct {
	Npc     NpcId
	Options []Option
	Lines   []uint16
}

type Dialog struct {
	f DialogFields
}

func (f DialogFields) Build() (Dialog, error) {
	f.Options = codec.Clone(f.Options)
	f.Lines = codec.Clone(f.Lines)
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Dialog{}, err
	}
	return Dialog{f}, nil
}

func (v Dialog) Npc() NpcId { return v.f.Npc }

func (v Dialog) Options() codec.List[Option] { return codec.ListOf(v.f.Options) }

func (v Dialog) Lines() codec.List[uint16] { return codec.ListOf(v.f.Lines) }

func (f DialogFields) encode(w *codec.Writer) {
	f.Npc.encode(w)
	w.Count(len(f.Options), 4)
	for _, e := range f.Options {
		e.encode(w)
	}
	if w.Err() == nil && !codec.Unique(len(f.Options), func(i, j int) bool { return f.Options[i] == f.Options[j] }) {
		w.Fail(codec.ErrRule)
	}
	w.Count(len(f.Lines), 8)
	for _, e := range f.Lines {
		w.U16(e)
	}
	if w.Err() == nil && slices.ContainsFunc(f.Lines, func(e uint16) bool { return !(e >= 1 && e <= 500) }) {
		w.Fail(codec.ErrRule)
	}
}

func decodeDialog(r *codec.Reader) Dialog {
	var f DialogFields
	f.Npc = decodeNpcId(r)
	if n := r.Count(4, 1); n > 0 {
		f.Options = make([]Option, n)
		for i := range f.Options {
			f.Options[i] = decodeOption(r)
		}
	}
	if r.Err() == nil && !codec.Unique(len(f.Options), func(i, j int) bool { return f.Options[i] == f.Options[j] }) {
		r.Fail(codec.ErrRule)
	}
	if n := r.Count(8, 2); n > 0 {
		f.Lines = make([]uint16, n)
		for i := range f.Lines {
			f.Lines[i] = r.U16()
		}
	}
	if r.Err() == nil && slices.ContainsFunc(f.Lines, func(e uint16) bool { return !(e >= 1 && e <= 500) }) {
		r.Fail(codec.ErrRule)
	}
	return Dialog{f}
}

func (f DialogFields) appendText(b []byte) []byte {
	b = append(b, "dialog{npc:"...)
	b = f.Npc.appendText(b)
	b = append(b, " options:"...)
	b = append(b, '[')
	for i, e := range f.Options {
		if i > 0 {
			b = append(b, ' ')
		}
		b = append(b, e.String()...)
	}
	b = append(b, ']')
	b = append(b, " lines:"...)
	b = append(b, '[')
	for i, e := range f.Lines {
		if i > 0 {
			b = append(b, ' ')
		}
		b = strconv.AppendUint(b, uint64(e), 10)
	}
	b = append(b, ']')
	return append(b, '}')
}

func (v Dialog) String() string { return string(v.f.appendText(nil)) }

func (Dialog) MessageID() uint32 { return 6 }

func (Dialog) Channel() codec.Channel { return codec.ChannelEvents }

func (Dialog) eventsMsg() {}

func (v Dialog) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(6)
	v.f.encode(&w)
	return w.Result()
}

type PickFields struct {
	Npc    NpcId
	Option Option
}

type Pick struct {
	f PickFields
}

func (f PickFields) Build() (Pick, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Pick{}, err
	}
	return Pick{f}, nil
}

func (v Pick) Npc() NpcId { return v.f.Npc }

func (v Pick) Option() Option { return v.f.Option }

func (f PickFields) encode(w *codec.Writer) {
	f.Npc.encode(w)
	f.Option.encode(w)
	if w.Err() == nil && !(f.Option == OptionAcceptQuest || f.Option == OptionTurnInQuest || f.Option == OptionStopTalking) {
		w.Fail(codec.ErrRule)
	}
}

func decodePick(r *codec.Reader) Pick {
	var f PickFields
	f.Npc = decodeNpcId(r)
	f.Option = decodeOption(r)
	if r.Err() == nil && !(f.Option == OptionAcceptQuest || f.Option == OptionTurnInQuest || f.Option == OptionStopTalking) {
		r.Fail(codec.ErrRule)
	}
	return Pick{f}
}

func (f PickFields) appendText(b []byte) []byte {
	b = append(b, "pick{npc:"...)
	b = f.Npc.appendText(b)
	b = append(b, " option:"...)
	b = append(b, f.Option.String()...)
	return append(b, '}')
}

func (v Pick) String() string { return string(v.f.appendText(nil)) }

func (Pick) MessageID() uint32 { return 7 }

func (Pick) Channel() codec.Channel { return codec.ChannelIntents }

func (Pick) intentsMsg() {}

func (v Pick) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(7)
	v.f.encode(&w)
	return w.Result()
}

type GiveFields struct {
	Npc  NpcId
	Slot uint8
}

type Give struct {
	f GiveFields
}

func (f GiveFields) Build() (Give, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Give{}, err
	}
	return Give{f}, nil
}

func (v Give) Npc() NpcId { return v.f.Npc }

func (v Give) Slot() uint8 { return v.f.Slot }

func (f GiveFields) encode(w *codec.Writer) {
	f.Npc.encode(w)
	w.U8(f.Slot)
	if w.Err() == nil && !(f.Slot <= 39) {
		w.Fail(codec.ErrRule)
	}
}

func decodeGive(r *codec.Reader) Give {
	var f GiveFields
	f.Npc = decodeNpcId(r)
	f.Slot = r.U8()
	if r.Err() == nil && !(f.Slot <= 39) {
		r.Fail(codec.ErrRule)
	}
	return Give{f}
}

func (f GiveFields) appendText(b []byte) []byte {
	b = append(b, "give{npc:"...)
	b = f.Npc.appendText(b)
	b = append(b, " slot:"...)
	b = strconv.AppendUint(b, uint64(f.Slot), 10)
	return append(b, '}')
}

func (v Give) String() string { return string(v.f.appendText(nil)) }

func (Give) MessageID() uint32 { return 8 }

func (Give) Channel() codec.Channel { return codec.ChannelIntents }

func (Give) intentsMsg() {}

func (v Give) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(8)
	v.f.encode(&w)
	return w.Result()
}

type TradeFields struct {
	From   PlayerId
	Offers []Offer
}

type Trade struct {
	f TradeFields
}

func (f TradeFields) Build() (Trade, error) {
	f.Offers = codec.Clone(f.Offers)
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Trade{}, err
	}
	return Trade{f}, nil
}

func (v Trade) From() PlayerId { return v.f.From }

func (v Trade) Offers() codec.List[Offer] { return codec.ListOf(v.f.Offers) }

func (f TradeFields) encode(w *codec.Writer) {
	f.From.encode(w)
	w.Count(len(f.Offers), 8)
	for _, e := range f.Offers {
		e.f.encode(w)
	}
	if w.Err() == nil && !codec.Unique(len(f.Offers), func(i, j int) bool { return f.Offers[i].f.Item == f.Offers[j].f.Item }) {
		w.Fail(codec.ErrRule)
	}
	if w.Err() == nil && slices.ContainsFunc(f.Offers, func(e Offer) bool { return !(e.f.Owner == f.From) }) {
		w.Fail(codec.ErrRule)
	}
}

func decodeTrade(r *codec.Reader) Trade {
	var f TradeFields
	f.From = decodePlayerId(r)
	if n := r.Count(8, 4); n > 0 {
		f.Offers = make([]Offer, n)
		for i := range f.Offers {
			f.Offers[i] = decodeOffer(r)
		}
	}
	if r.Err() == nil && !codec.Unique(len(f.Offers), func(i, j int) bool { return f.Offers[i].f.Item == f.Offers[j].f.Item }) {
		r.Fail(codec.ErrRule)
	}
	if r.Err() == nil && slices.ContainsFunc(f.Offers, func(e Offer) bool { return !(e.f.Owner == f.From) }) {
		r.Fail(codec.ErrRule)
	}
	return Trade{f}
}

func (f TradeFields) appendText(b []byte) []byte {
	b = append(b, "trade{from:"...)
	b = f.From.appendText(b)
	b = append(b, " offers:"...)
	b = append(b, '[')
	for i, e := range f.Offers {
		if i > 0 {
			b = append(b, ' ')
		}
		b = e.f.appendText(b)
	}
	b = append(b, ']')
	return append(b, '}')
}

func (v Trade) String() string { return string(v.f.appendText(nil)) }

func (Trade) MessageID() uint32 { return 9 }

func (Trade) Channel() codec.Channel { return codec.ChannelEvents }

func (Trade) eventsMsg() {}

func (v Trade) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(9)
	v.f.encode(&w)
	return w.Result()
}

type DuelFields struct {
	Challenger PlayerId
	Target     PlayerId
}

type Duel struct {
	f DuelFields
}

func (f DuelFields) Build() (Duel, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Duel{}, err
	}
	return Duel{f}, nil
}

func (v Duel) Challenger() PlayerId { return v.f.Challenger }

func (v Duel) Target() PlayerId { return v.f.Target }

func (f DuelFields) encode(w *codec.Writer) {
	f.Challenger.encode(w)
	f.Target.encode(w)
	if w.Err() == nil && !(f.Target != f.Challenger) {
		w.Fail(codec.ErrRule)
	}
}

func decodeDuel(r *codec.Reader) Duel {
	var f DuelFields
	f.Challenger = decodePlayerId(r)
	f.Target = decodePlayerId(r)
	if r.Err() == nil && !(f.Target != f.Challenger) {
		r.Fail(codec.ErrRule)
	}
	return Duel{f}
}

func (f DuelFields) appendText(b []byte) []byte {
	b = append(b, "duel{challenger:"...)
	b = f.Challenger.appendText(b)
	b = append(b, " target:"...)
	b = f.Target.appendText(b)
	return append(b, '}')
}

func (v Duel) String() string { return string(v.f.appendText(nil)) }

func (Duel) MessageID() uint32 { return 10 }

func (Duel) Channel() codec.Channel { return codec.ChannelEvents }

func (Duel) eventsMsg() {}

func (v Duel) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(10)
	v.f.encode(&w)
	return w.Result()
}

type ZoneFields struct {
	Lo   float64
	Hi   float64
	Tilt int8
}

type Zone struct {
	f ZoneFields
}

func (f ZoneFields) Build() (Zone, error) {
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Zone{}, err
	}
	return Zone{f}, nil
}

func (v Zone) Lo() float64 { return v.f.Lo }

func (v Zone) Hi() float64 { return v.f.Hi }

func (v Zone) Tilt() int8 { return v.f.Tilt }

func (f ZoneFields) encode(w *codec.Writer) {
	w.Quant(f.Lo, quantCoord)
	if w.Err() == nil && !(quantCoord.Step(f.Lo) >= 8 && quantCoord.Step(f.Lo) <= 72) {
		w.Fail(codec.ErrRule)
	}
	w.Quant(f.Hi, quantCoord)
	if w.Err() == nil && !(quantCoord.Step(f.Hi) <= 61) {
		w.Fail(codec.ErrRule)
	}
	w.U8(uint8(f.Tilt))
	if w.Err() == nil && !(f.Tilt >= -45 && f.Tilt <= 45) {
		w.Fail(codec.ErrRule)
	}
	if w.Err() == nil && !(quantCoord.Step(f.Lo) <= quantCoord.Step(f.Hi)) {
		w.Fail(codec.ErrRule)
	}
}

func decodeZone(r *codec.Reader) Zone {
	var f ZoneFields
	f.Lo = r.Quant(quantCoord)
	if r.Err() == nil && !(quantCoord.Step(f.Lo) >= 8 && quantCoord.Step(f.Lo) <= 72) {
		r.Fail(codec.ErrRule)
	}
	f.Hi = r.Quant(quantCoord)
	if r.Err() == nil && !(quantCoord.Step(f.Hi) <= 61) {
		r.Fail(codec.ErrRule)
	}
	f.Tilt = int8(r.U8())
	if r.Err() == nil && !(f.Tilt >= -45 && f.Tilt <= 45) {
		r.Fail(codec.ErrRule)
	}
	if r.Err() == nil && !(quantCoord.Step(f.Lo) <= quantCoord.Step(f.Hi)) {
		r.Fail(codec.ErrRule)
	}
	return Zone{f}
}

func (f ZoneFields) appendText(b []byte) []byte {
	b = append(b, "zone{lo:"...)
	b = strconv.AppendFloat(b, f.Lo, 'g', -1, 64)
	b = append(b, " hi:"...)
	b = strconv.AppendFloat(b, f.Hi, 'g', -1, 64)
	b = append(b, " tilt:"...)
	b = strconv.AppendInt(b, int64(f.Tilt), 10)
	return append(b, '}')
}

func (v Zone) String() string { return string(v.f.appendText(nil)) }

func (Zone) MessageID() uint32 { return 11 }

func (Zone) Channel() codec.Channel { return codec.ChannelState }

func (Zone) stateMsg() {}

func (v Zone) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(11)
	v.f.encode(&w)
	return w.Result()
}

type TagFields struct {
	Who    Who
	Other  Who
	Crowd  []Who
	By     codec.Opt[Who]
	Note   codec.Opt[string]
	Weight codec.Opt[uint8]
	Pair   codec.Opt[Pair]
	Slots  []codec.Opt[uint8]
}

type Tag struct {
	f TagFields
}

func (f TagFields) Build() (Tag, error) {
	f.Crowd = codec.Clone(f.Crowd)
	f.Slots = codec.Clone(f.Slots)
	w := codec.NewChecker()
	f.encode(&w)
	if err := w.Err(); err != nil {
		return Tag{}, err
	}
	return Tag{f}, nil
}

func (v Tag) Who() Who { return v.f.Who }

func (v Tag) Other() Who { return v.f.Other }

func (v Tag) Crowd() codec.List[Who] { return codec.ListOf(v.f.Crowd) }

func (v Tag) By() codec.Opt[Who] { return v.f.By }

func (v Tag) Note() codec.Opt[string] { return v.f.Note }

func (v Tag) Weight() codec.Opt[uint8] { return v.f.Weight }

func (v Tag) Pair() codec.Opt[Pair] { return v.f.Pair }

func (v Tag) Slots() codec.List[codec.Opt[uint8]] { return codec.ListOf(v.f.Slots) }

func (f TagFields) encode(w *codec.Writer) {
	encodeWho(w, f.Who)
	encodeWho(w, f.Other)
	w.Count(len(f.Crowd), 3)
	for _, e := range f.Crowd {
		encodeWho(w, e)
	}
	if w.Err() == nil && !codec.Unique(len(f.Crowd), func(i, j int) bool { return f.Crowd[i] == f.Crowd[j] }) {
		w.Fail(codec.ErrRule)
	}
	if v, ok := f.By.Get(); ok {
		w.Bool(true)
		encodeWho(w, v)
	} else {
		w.Bool(false)
	}
	if v, ok := f.Note.Get(); ok {
		w.Bool(true)
		w.String(v, 4)
	} else {
		w.Bool(false)
	}
	if v, ok := f.Weight.Get(); ok {
		w.Bool(true)
		w.U8(v)
	} else {
		w.Bool(false)
	}
	if v, ok := f.Weight.Get(); ok {
		if w.Err() == nil && !(v >= 1 && v <= 9) {
			w.Fail(codec.ErrRule)
		}
	}
	if v, ok := f.Pair.Get(); ok {
		w.Bool(true)
		v.f.encode(w)
	} else {
		w.Bool(false)
	}
	w.Count(len(f.Slots), 2)
	for _, e := range f.Slots {
		if v, ok := e.Get(); ok {
			w.Bool(true)
			w.U8(v)
		} else {
			w.Bool(false)
		}
	}
	if w.Err() == nil && !(f.Other != f.Who) {
		w.Fail(codec.ErrRule)
	}
	if w.Err() == nil && !slices.ContainsFunc(f.Crowd, func(e Who) bool { return e == f.Who }) {
		w.Fail(codec.ErrRule)
	}
}

func decodeTag(r *codec.Reader) Tag {
	var f TagFields
	f.Who = decodeWho(r)
	f.Other = decodeWho(r)
	if n := r.Count(3, 3); n > 0 {
		f.Crowd = make([]Who, n)
		for i := range f.Crowd {
			f.Crowd[i] = decodeWho(r)
		}
	}
	if r.Err() == nil && !codec.Unique(len(f.Crowd), func(i, j int) bool { return f.Crowd[i] == f.Crowd[j] }) {
		r.Fail(codec.ErrRule)
	}
	f.By = codec.ReadOpt(r, func(r *codec.Reader) Who { return decodeWho(r) })
	f.Note = codec.ReadOpt(r, func(r *codec.Reader) string { return r.String(4) })
	f.Weight = codec.ReadOpt(r, func(r *codec.Reader) uint8 { return r.U8() })
	if v, ok := f.Weight.Get(); ok {
		if r.Err() == nil && !(v >= 1 && v <= 9) {
			r.Fail(codec.ErrRule)
		}
	}
	f.Pair = codec.ReadOpt(r, func(r *codec.Reader) Pair { return decodePair(r) })
	if n := r.Count(2, 1); n > 0 {
		f.Slots = make([]codec.Opt[uint8], n)
		for i := range f.Slots {
			f.Slots[i] = codec.ReadOpt(r, func(r *codec.Reader) uint8 { return r.U8() })
		}
	}
	if r.Err() == nil && !(f.Other != f.Who) {
		r.Fail(codec.ErrRule)
	}
	if r.Err() == nil && !slices.ContainsFunc(f.Crowd, func(e Who) bool { return e == f.Who }) {
		r.Fail(codec.ErrRule)
	}
	return Tag{f}
}

func (f TagFields) appendText(b []byte) []byte {
	b = append(b, "tag{who:"...)
	b = appendWhoText(b, f.Who)
	b = append(b, " other:"...)
	b = appendWhoText(b, f.Other)
	b = append(b, " crowd:"...)
	b = append(b, '[')
	for i, e := range f.Crowd {
		if i > 0 {
			b = append(b, ' ')
		}
		b = appendWhoText(b, e)
	}
	b = append(b, ']')
	b = append(b, " by:"...)
	if v, ok := f.By.Get(); ok {
		b = appendWhoText(b, v)
	} else {
		b = append(b, '_')
	}
	b = append(b, " note:"...)
	if v, ok := f.Note.Get(); ok {
		b = strconv.AppendQuoteToASCII(b, v)
	} else {
		b = append(b, '_')
	}
	b = append(b, " weight:"...)
	if v, ok := f.Weight.Get(); ok {
		b = strconv.AppendUint(b, uint64(v), 10)
	} else {
		b = append(b, '_')
	}
	b = append(b, " pair:"...)
	if v, ok := f.Pair.Get(); ok {
		b = v.f.appendText(b)
	} else {
		b = append(b, '_')
	}
	b = append(b, " slots:"...)
	b = append(b, '[')
	for i, e := range f.Slots {
		if i > 0 {
			b = append(b, ' ')
		}
		if v, ok := e.Get(); ok {
			b = strconv.AppendUint(b, uint64(v), 10)
		} else {
			b = append(b, '_')
		}
	}
	b = append(b, ']')
	return append(b, '}')
}

func (v Tag) String() string { return string(v.f.appendText(nil)) }

func (Tag) MessageID() uint32 { return 12 }

func (Tag) Channel() codec.Channel { return codec.ChannelState }

func (Tag) stateMsg() {}

func (v Tag) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(12)
	v.f.encode(&w)
	return w.Result()
}

func DecodeNextState(r *codec.Reader) (StateMsg, error) {
	var m StateMsg
	switch r.Varint() {
	case 11:
		m = decodeZone(r)
	case 12:
		m = decodeTag(r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeState(b []byte) (StateMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextState(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeNextEvents(r *codec.Reader) (EventsMsg, error) {
	var m EventsMsg
	switch r.Varint() {
	case 1:
		m = decodeProbe(r)
	case 3:
		m = decodeCrowd(r)
	case 4:
		m = decodeParty(r)
	case 5:
		m = decodeInventory(r)
	case 6:
		m = decodeDialog(r)
	case 9:
		m = decodeTrade(r)
	case 10:
		m = decodeDuel(r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeEvents(b []byte) (EventsMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextEvents(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeNextInput(r *codec.Reader) (InputMsg, error) {
	var m InputMsg
	switch r.Varint() {
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeInput(b []byte) (InputMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextInput(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeNextIntents(r *codec.Reader) (IntentsMsg, error) {
	var m IntentsMsg
	switch r.Varint() {
	case 2:
		m = decodePing(r)
	case 7:
		m = decodePick(r)
	case 8:
		m = decodeGive(r)
	default:
		r.Fail(codec.ErrUnknownMessage)
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

func DecodeIntents(b []byte) (IntentsMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNextIntents(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}
