package main

import (
	"fmt"
	"strings"
)

var cppPrim = map[string]string{
	"u8": "std::uint8_t", "u16": "std::uint16_t", "u32": "std::uint32_t", "u64": "std::uint64_t",
	"i8": "std::int8_t", "i16": "std::int16_t", "i32": "std::int32_t", "i64": "std::int64_t",
	"bool": "bool", "f32": "float",
}

// cppWire maps each primitive to the Writer/Reader method that carries it and
// the unsigned type a signed value converts through.
var cppWire = map[string][2]string{
	"u8": {"u8", ""}, "u16": {"u16", ""}, "u32": {"u32", ""}, "u64": {"u64", ""},
	"i8": {"u8", "std::uint8_t"}, "i16": {"u16", "std::uint16_t"}, "i32": {"u32", "std::uint32_t"}, "i64": {"u64", "std::uint64_t"},
	"bool": {"boolean", ""}, "f32": {"f32", ""},
}

func cppType(t Type) string {
	switch t.Kind {
	case KindPrim:
		return cppPrim[t.Prim]
	case KindQuant:
		return "double"
	case KindString:
		return "std::string"
	case KindList:
		return "std::vector<" + cppType(*t.Elem) + ">"
	case KindEnum:
		return t.Enum.Name
	case KindHandle:
		return t.Handle.Name
	default:
		return t.Struct.Name
	}
}

func cppInit(t Type) string {
	switch t.Kind {
	case KindPrim:
		if t.Prim == "bool" {
			return " = false"
		}
		return " = 0"
	case KindQuant:
		return " = 0"
	default:
		return "{}"
	}
}

func cppEncode(t Type, expr string) string {
	switch t.Kind {
	case KindPrim:
		wire := cppWire[t.Prim]
		if wire[1] != "" {
			return fmt.Sprintf("w.%s(static_cast<%s>(%s));", wire[0], wire[1], expr)
		}
		return fmt.Sprintf("w.%s(%s);", wire[0], expr)
	case KindQuant:
		return fmt.Sprintf("w.quant(%s, quant_%s);", expr, t.Quant.Name)
	case KindString:
		return fmt.Sprintf("w.string(%s, %d);", expr, t.Bound)
	case KindList:
		return fmt.Sprintf("w.count(%s.size(), %d);\n    for (const auto& e : %s) {\n        %s\n    }", expr, t.Bound, expr, cppEncode(*t.Elem, "e"))
	default:
		return fmt.Sprintf("write(w, %s);", expr)
	}
}

func cppDecode(t Type) string {
	switch t.Kind {
	case KindPrim:
		wire := cppWire[t.Prim]
		if wire[1] != "" {
			return fmt.Sprintf("static_cast<%s>(r.%s())", cppPrim[t.Prim], wire[0])
		}
		return fmt.Sprintf("r.%s()", wire[0])
	case KindQuant:
		return fmt.Sprintf("r.quant(quant_%s)", t.Quant.Name)
	case KindString:
		return fmt.Sprintf("r.string(%d)", t.Bound)
	default:
		return fmt.Sprintf("read_%s(r)", cppType(t))
	}
}

func cppDecodeField(f Field) string {
	dst := "v." + f.Name
	if f.Type.Kind != KindList {
		return fmt.Sprintf("    %s = %s;\n", dst, cppDecode(f.Type))
	}
	return fmt.Sprintf("    %s.resize(r.count(%d));\n    for (std::size_t i = 0; i < %s.size(); ++i) {\n        %s[i] = %s;\n    }\n",
		dst, f.Type.Bound, dst, dst, cppDecode(*f.Type.Elem))
}

func cppStructBody(b *strings.Builder, name string, fields []Field) {
	for _, f := range fields {
		fmt.Fprintf(b, "    %s %s%s;\n", cppType(f.Type), f.Name, cppInit(f.Type))
	}
	fmt.Fprintf(b, "\n    bool operator==(const %s&) const = default;\n};\n\n", name)
}

func cppChannel(c string) string { return "codec::Channel::" + c }

func genCppHeader(s *Schema, schemaPath, ns string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by wiregen from %s. DO NOT EDIT.\n\n#pragma once\n\n", schemaPath)
	b.WriteString("#include <cstdint>\n#include <expected>\n#include <span>\n#include <string>\n#include <variant>\n#include <vector>\n\n#include \"marque/wire/codec.hpp\"\n\n")
	fmt.Fprintf(&b, "namespace %s {\n\n", ns)
	fmt.Fprintf(&b, "inline constexpr std::uint64_t schema_hash = 0x%016xULL;\n\n", s.Hash())

	for _, h := range s.Handles {
		fmt.Fprintf(&b, "// Pairs a slot index with the generation that slot had when the entity was\n// created, so a reused index never names the old entity.\nstruct %s {\n    std::uint32_t index = 0;\n    std::uint32_t gen = 0;\n\n    bool operator==(const %s&) const = default;\n};\n\n", h.Name, h.Name)
	}
	for _, e := range s.Enums {
		fmt.Fprintf(&b, "enum class %s : std::uint32_t {\n", e.Name)
		for _, m := range e.Members {
			fmt.Fprintf(&b, "    %s = %d,\n", m.Name, m.Value)
		}
		b.WriteString("};\n\n")
	}
	for _, st := range s.Structs {
		fmt.Fprintf(&b, "struct %s {\n", st.Name)
		cppStructBody(&b, st.Name, st.Fields)
	}
	for _, m := range s.Messages {
		name := goName(m.Name)
		fmt.Fprintf(&b, "struct %s {\n    static constexpr std::uint32_t message_id = %d;\n    static constexpr codec::Channel channel = %s;\n\n", name, m.ID, cppChannel(m.Channel))
		cppStructBody(&b, name, m.Fields)
	}
	for _, d := range cppDirections(s) {
		fmt.Fprintf(&b, "using %s = std::variant<%s>;\n", d.alias, strings.Join(d.names, ", "))
	}
	b.WriteString("\n")
	for _, m := range s.Messages {
		fmt.Fprintf(&b, "std::expected<void, codec::Error> encode(const %s& m, std::vector<std::uint8_t>& out);\n", goName(m.Name))
	}
	b.WriteString("\n")
	for _, d := range cppDirections(s) {
		fmt.Fprintf(&b, "// Decodes exactly one message; any byte left over is an error.\nstd::expected<%s, codec::Error> %s(std::span<const std::uint8_t> bytes);\n", d.alias, d.fn)
	}
	b.WriteString("\n}\n")
	return []byte(b.String())
}

type cppDirection struct {
	alias, fn string
	msgs      []*Message
	names     []string
}

// cppDirections skips a direction with no messages, since std::variant<> is
// ill-formed.
func cppDirections(s *Schema) []cppDirection {
	var out []cppDirection
	for _, d := range []cppDirection{{alias: "ToServer", fn: "decode_to_server"}, {alias: "ToClient", fn: "decode_to_client"}} {
		d.msgs = s.MessagesTo(map[string]string{"ToServer": "c2s", "ToClient": "s2c"}[d.alias])
		for _, m := range d.msgs {
			d.names = append(d.names, goName(m.Name))
		}
		if len(d.msgs) > 0 {
			out = append(out, d)
		}
	}
	return out
}

func cppRecordCodec(b *strings.Builder, name string, fields []Field) {
	fmt.Fprintf(b, "[[maybe_unused]] void write(codec::Writer& w, const %s& v) {\n", name)
	if len(fields) == 0 {
		b.WriteString("    (void)w;\n    (void)v;\n")
	}
	for _, f := range fields {
		fmt.Fprintf(b, "    %s\n", cppEncode(f.Type, "v."+f.Name))
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "[[maybe_unused]] %s read_%s(codec::Reader& r) {\n    %s v;\n", name, name, name)
	if len(fields) == 0 {
		b.WriteString("    (void)r;\n")
	}
	for _, f := range fields {
		b.WriteString(cppDecodeField(f))
	}
	b.WriteString("    return v;\n}\n\n")
}

func genCppSource(s *Schema, schemaPath, ns, header string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by wiregen from %s. DO NOT EDIT.\n\n#include \"%s\"\n\n", schemaPath, header)
	fmt.Fprintf(&b, "namespace %s {\n\nnamespace {\n\n", ns)
	for _, q := range s.Quants {
		fmt.Fprintf(&b, "[[maybe_unused]] constexpr codec::Quant quant_%s{%d, %d, %d, %d, %d};\n", q.Name, q.Min, q.Max, q.PerUnit, q.Steps(), q.Width())
	}
	if len(s.Quants) > 0 {
		b.WriteString("\n")
	}
	for _, h := range s.Handles {
		fmt.Fprintf(&b, "[[maybe_unused]] void write(codec::Writer& w, const %[1]s& v) {\n    w.varint(v.index);\n    w.varint(v.gen);\n}\n\n[[maybe_unused]] %[1]s read_%[1]s(codec::Reader& r) {\n    %[1]s v;\n    v.index = r.varint();\n    v.gen = r.varint();\n    return v;\n}\n\n", h.Name)
	}
	for _, e := range s.Enums {
		fmt.Fprintf(&b, "[[maybe_unused]] bool valid(%s v) {\n    switch (v) {\n", e.Name)
		for _, m := range e.Members {
			fmt.Fprintf(&b, "    case %s::%s:\n", e.Name, m.Name)
		}
		b.WriteString("        return true;\n    }\n    return false;\n}\n\n")
		fmt.Fprintf(&b, "[[maybe_unused]] void write(codec::Writer& w, %[1]s v) {\n    if (!valid(v)) {\n        w.fail(codec::Error::bad_enum);\n        return;\n    }\n    w.varint(static_cast<std::uint32_t>(v));\n}\n\n[[maybe_unused]] %[1]s read_%[1]s(codec::Reader& r) {\n    const auto v = static_cast<%[1]s>(r.varint());\n    if (!r.failed() && !valid(v)) r.fail(codec::Error::bad_enum);\n    return v;\n}\n\n", e.Name)
	}
	for _, st := range s.Structs {
		cppRecordCodec(&b, st.Name, st.Fields)
	}
	for _, m := range s.Messages {
		cppRecordCodec(&b, goName(m.Name), m.Fields)
	}
	b.WriteString("}\n\n")
	for _, m := range s.Messages {
		name := goName(m.Name)
		fmt.Fprintf(&b, "std::expected<void, codec::Error> encode(const %[1]s& m, std::vector<std::uint8_t>& out) {\n    codec::Writer w{out};\n    w.varint(%[1]s::message_id);\n    write(w, m);\n    return w.finish();\n}\n\n", name)
	}
	for _, d := range cppDirections(s) {
		fmt.Fprintf(&b, "std::expected<%s, codec::Error> %s(std::span<const std::uint8_t> bytes) {\n    codec::Reader r{bytes};\n    %s m;\n    switch (r.varint()) {\n", d.alias, d.fn, d.alias)
		for _, name := range d.names {
			fmt.Fprintf(&b, "    case %[1]s::message_id:\n        m = read_%[1]s(r);\n        break;\n", name)
		}
		b.WriteString("    default:\n        r.fail(codec::Error::unknown_message);\n        break;\n    }\n    if (auto err = r.finish()) return std::unexpected(*err);\n    return m;\n}\n\n")
	}
	b.WriteString("}\n")
	return []byte(b.String())
}
