package main

import (
	"fmt"
	"go/format"
	"strings"
)

const codecImport = "github.com/devarminas/marque/server/internal/wire/codec"

var goPrim = map[string]string{
	"u8": "uint8", "u16": "uint16", "u32": "uint32", "u64": "uint64",
	"i8": "int8", "i16": "int16", "i32": "int32", "i64": "int64",
	"bool": "bool", "f32": "float32",
}

var goWire = map[string][2]string{
	"u8": {"U8", ""}, "u16": {"U16", ""}, "u32": {"U32", ""}, "u64": {"U64", ""},
	"i8": {"U8", "uint8"}, "i16": {"U16", "uint16"}, "i32": {"U32", "uint32"}, "i64": {"U64", "uint64"},
	"bool": {"Bool", ""}, "f32": {"F32", ""},
}

func goType(t Type) string {
	switch t.Kind {
	case KindPrim:
		return goPrim[t.Prim]
	case KindQuant:
		return "float64"
	case KindString:
		return "string"
	case KindList:
		return "[]" + goType(*t.Elem)
	case KindEnum:
		return t.Enum.Name
	case KindHandle:
		return t.Handle.Name
	default:
		return t.Struct.Name
	}
}

func goEncode(t Type, expr string) string {
	switch t.Kind {
	case KindPrim:
		wire := goWire[t.Prim]
		if wire[1] != "" {
			return fmt.Sprintf("w.%s(%s(%s))", wire[0], wire[1], expr)
		}
		return fmt.Sprintf("w.%s(%s)", wire[0], expr)
	case KindQuant:
		return fmt.Sprintf("w.Quant(%s, quant%s)", expr, goName(t.Quant.Name))
	case KindString:
		return fmt.Sprintf("w.String(%s, %d)", expr, t.Bound)
	case KindList:
		return fmt.Sprintf("w.Count(len(%s), %d)\nfor _, e := range %s {\n%s\n}", expr, t.Bound, expr, goEncode(*t.Elem, "e"))
	default:
		return fmt.Sprintf("%s.encode(w)", expr)
	}
}

func goDecode(t Type) string {
	switch t.Kind {
	case KindPrim:
		wire := goWire[t.Prim]
		if wire[1] != "" {
			return fmt.Sprintf("%s(r.%s())", goPrim[t.Prim], wire[0])
		}
		return fmt.Sprintf("r.%s()", wire[0])
	case KindQuant:
		return fmt.Sprintf("r.Quant(quant%s)", goName(t.Quant.Name))
	case KindString:
		return fmt.Sprintf("r.String(%d)", t.Bound)
	default:
		return fmt.Sprintf("decode%s(r)", goType(t))
	}
}

func goDecodeField(f Field) string {
	dst := "v." + goName(f.Name)
	if f.Type.Kind != KindList {
		return fmt.Sprintf("%s = %s", dst, goDecode(f.Type))
	}
	return fmt.Sprintf("if n := r.Count(%d, %d); n > 0 {\n%s = make(%s, n)\nfor i := range %s {\n%s[i] = %s\n}\n}",
		f.Type.Bound, f.Type.Elem.MinSize(), dst, goType(f.Type), dst, dst, goDecode(*f.Type.Elem))
}

func goRecord(b *strings.Builder, name, textName string, fields []Field) {
	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, f := range fields {
		fmt.Fprintf(b, "%s %s\n", goName(f.Name), goType(f.Type))
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "func (v %s) encode(w *codec.Writer) {\n", name)
	for _, f := range fields {
		b.WriteString(goEncode(f.Type, "v."+goName(f.Name)) + "\n")
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "func decode%s(r *codec.Reader) (v %s) {\n", name, name)
	for _, f := range fields {
		b.WriteString(goDecodeField(f) + "\n")
	}
	b.WriteString("return v\n}\n\n")

	verbs, args := make([]string, len(fields)), make([]string, len(fields))
	for i, f := range fields {
		verb := "%v"
		if f.Type.Kind == KindString {
			verb = "%q"
		}
		verbs[i] = f.Name + ":" + verb
		args[i] = ", v." + goName(f.Name)
	}
	fmt.Fprintf(b, "func (v %s) String() string {\nreturn fmt.Sprintf(%q%s)\n}\n\n",
		name, textName+"{"+strings.Join(verbs, " ")+"}", strings.Join(args, ""))
}

func genGo(s *Schema, schemaPath, pkg string) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by wiregen from %s. DO NOT EDIT.\n\n", schemaPath)
	fmt.Fprintf(&b, "package %s\n\nimport (\n\"fmt\"\n\n%q\n)\n\n", pkg, codecImport)
	fmt.Fprintf(&b, "const SchemaHash uint64 = 0x%016x\n\n", s.Hash())

	b.WriteString(`type Message interface {
	MessageID() uint32
	Channel() codec.Channel
	Append(dst []byte) ([]byte, error)
	String() string
}

`)
	for _, ch := range channels {
		fmt.Fprintf(&b, "type %[1]sMsg interface {\nMessage\n%[2]sMsg()\n}\n\n", goName(ch), ch)
	}

	for _, q := range s.Quants {
		fmt.Fprintf(&b, "var quant%s = codec.Quant{Min: %d, Max: %d, PerUnit: %d, Steps: %d, Width: %d}\n\n",
			goName(q.Name), q.Min, q.Max, q.PerUnit, q.Steps(), q.Width())
	}

	for _, h := range s.Handles {
		fmt.Fprintf(&b, `type %[1]s struct {
	Index uint32
	Gen   uint32
}

func (v %[1]s) encode(w *codec.Writer) {
	w.Varint(v.Index)
	w.Varint(v.Gen)
}

func decode%[1]s(r *codec.Reader) (v %[1]s) {
	v.Index = r.Varint()
	v.Gen = r.Varint()
	return v
}

func (v %[1]s) String() string { return fmt.Sprintf("%[1]s(%%d/%%d)", v.Index, v.Gen) }

`, h.Name)
	}

	for _, e := range s.Enums {
		fmt.Fprintf(&b, "type %s uint32\n\nconst (\n", e.Name)
		for _, m := range e.Members {
			fmt.Fprintf(&b, "%s%s %s = %d\n", e.Name, goName(m.Name), e.Name, m.Value)
		}
		b.WriteString(")\n\n")
		fmt.Fprintf(&b, "func (v %s) String() string {\nswitch v {\n", e.Name)
		for _, m := range e.Members {
			fmt.Fprintf(&b, "case %s%s:\nreturn %q\n", e.Name, goName(m.Name), m.Name)
		}
		fmt.Fprintf(&b, "}\nreturn fmt.Sprintf(\"%s(%%d)\", uint32(v))\n}\n\n", e.Name)
		fmt.Fprintf(&b, "func (v %s) valid() bool {\nswitch v {\ncase ", e.Name)
		for i, m := range e.Members {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(e.Name + goName(m.Name))
		}
		b.WriteString(":\nreturn true\n}\nreturn false\n}\n\n")
		fmt.Fprintf(&b, `func (v %[1]s) encode(w *codec.Writer) {
	if !v.valid() {
		w.Fail(codec.ErrBadEnum)
		return
	}
	w.Varint(uint32(v))
}

func decode%[1]s(r *codec.Reader) %[1]s {
	v := %[1]s(r.Varint())
	if r.Err() == nil && !v.valid() {
		r.Fail(codec.ErrBadEnum)
	}
	return v
}

`, e.Name)
	}

	for _, st := range s.Structs {
		goRecord(&b, st.Name, st.Name, st.Fields)
	}

	for _, m := range s.Messages {
		name := goName(m.Name)
		goRecord(&b, name, m.Name, m.Fields)
		fmt.Fprintf(&b, `func (%[1]s) MessageID() uint32 { return %[2]d }

func (%[1]s) Channel() codec.Channel { return codec.Channel%[3]s }

func (%[1]s) %[4]sMsg() {}

func (v %[1]s) Append(dst []byte) ([]byte, error) {
	w := codec.NewWriter(dst)
	w.Varint(%[2]d)
	v.encode(&w)
	return w.Result()
}

`, name, m.ID, goName(m.Channel), m.Channel)
	}

	for _, ch := range channels {
		c := goName(ch)
		fmt.Fprintf(&b, "func DecodeNext%[1]s(r *codec.Reader) (%[1]sMsg, error) {\nvar m %[1]sMsg\nswitch r.Varint() {\n", c, ch)
		for _, m := range s.MessagesOn(ch) {
			fmt.Fprintf(&b, "case %d:\nm = decode%s(r)\n", m.ID, goName(m.Name))
		}
		b.WriteString("default:\nr.Fail(codec.ErrUnknownMessage)\n}\nif err := r.Err(); err != nil {\nreturn nil, err\n}\nreturn m, nil\n}\n\n")
		fmt.Fprintf(&b, `func Decode%[1]s(b []byte) (%[1]sMsg, error) {
	r := codec.NewReader(b)
	m, err := DecodeNext%[1]s(r)
	if err != nil {
		return nil, err
	}
	if err := r.Finish(); err != nil {
		return nil, err
	}
	return m, nil
}

`, c, ch)
	}

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated Go: %w\n%s", err, b.String())
	}
	return out, nil
}
